### ISSUE TITLE
VM freezes when Docker Container are running and VDP makes a Snapshot

### ISSUE THREAD

**Issue by hauihau** [vmware/open-vm-tools#122] opened 2016-12-13 10:13 UTC
We have some VMs running under OpenSUSE Leap 42.2 with docker 1.12.3. The VMs freeze, when VDP does its job. LEAP 42.1 and docker 1.9.1 didn't show this issue. open-vm-tools are installed with version open-vm-tools-10.0.7-1.1. It looks like the FS is not unquiesced.

Is there any way I can check this? Please let me kow what other information I should provide.

**Comment by hauihau** [comment] 2016-12-16 20:24
We have excluded the VMs from VDP and the issue didn't occur again.

**Comment by ravindravmw** [comment] 2016-12-21 00:39
For further debugging, could you please create /etc/vmware-tools/tools.conf in the guest with following contents?

# Start
[logging]
vmsvc.level=debug
vmsvc.handler=vmx

vmbackup.level=debug
vmbackup.handler=vmx
# End

Please try the operation, collect and share vmware.log from the VM's directory. Please don't attach the vmware.log file here, instead send it to me in an email. Thanks!

**Comment by ravindravmw** [comment] 2016-12-21 20:23
Please also share the output of 'mount' command from your VM, thanks!

**Comment by mibrault** [comment] 2017-01-16 13:22
I also have this problem, with CentOS 7.3 (last kernel 3.10.0-514.2.2.el7) and Docker 1.12.5 and vmware tools 10.0.9.55972.
As a workaround I stopped vmware-tools client on the VM.

**Comment by ravindravmw** [comment] 2017-01-25 19:23
Thanks @hauihau for providing the vmware.log. Looking at logs, I can confirm that this issue has been fixed in open-vm-tools 10.1.0.

**Comment by hauihau** [comment] 2017-01-25 19:23
@ravindravmw: I've sent you the vmware.log to the email address shown on your github profile page.

**Comment by hauihau** [comment] 2017-01-25 19:26
thanks. Could you tell me the line numbers in the log file?

Would you mind being a bit more specific what caused the issue and how it was fixed?

**Comment by ravindravmw** [comment] 2017-01-25 19:55
> thanks. Could you tell me the line numbers in the log file?

I will email you the details.

> Would you mind being a bit more specific what caused the issue and how it was fixed?

The issue is the order in which we quiesce the mount points. In previous versions of open-vm-tools. we were quiescing the mount points in the order we see them which leads to quiescing operation hanging for the mount points that are dependent on previous mount points. Docker creates some mount points that depend on previous mount points and therefore runs into this problem. This is pretty much the same scenario as issue #6. We fixed the order of mount points in open-vm-tools 10.1.0.

**Comment by hauihau** [comment] 2017-01-25 20:06
Thanks a lot! I've updated my opensuse bugzilla to request a version bump for open-vm-tools package.

**Comment by ravindravmw** [comment] 2017-01-25 21:06
That's done apparently in https://build.opensuse.org/request/show/443236.

**Comment by hauihau** [comment] 2017-01-25 21:51
Thats openSUSE Factory, nothing one should consider for production systems. We're using LEAP 42.2.

**Comment by kenljohnson** [comment] 2017-01-26 00:24
On Jan 25, 2017, at 13:06, Steffen Hau <notifications@github.com> wrote:
> 
> Thanks a lot! I've updated my opensuse bugzilla to request a version bump for open-vm-tools package.

Could you pls provide that bug #?

**Comment by kenljohnson** [comment] 2017-01-26 00:28
On Jan 25, 2017, at 14:51, Steffen Hau <notifications@github.com> wrote:
> 
> Thats openSUSE Factory, nothing one should consider for production systems. We're using LEAP 42.2.

We’re working on updating SLES 12 SP1 & SP2 to version 10.1.0. Once that’s complete we’ll submit the update to Leap 42.1 and 42.2. In the mean time, you can get access to these packages from our OBS development project here:

https://build.opensuse.org/package/show/Virtualization:VMware/open-vm-tools

HTH,
Ken

**Comment by hauihau** [comment] 2017-01-26 09:55
@kenljohnson: https://bugzilla.suse.com/show_bug.cgi?id=1015095

I've disabled open-vm-tools until the updated version reaches the leap repos.

**Comment by ravindravmw** [comment] 2017-03-04 23:12
Fix has been released in open-vm-tools 10.1.0.

**Closed by ravindravmw** 2017-03-04 23:12 UTC
