### ISSUE TITLE
3D graphics acceleration causes GNOME window display issues in Fedora 31

### ISSUE THREAD

**Issue by hermidalc** [vmware/open-vm-tools#400] opened 2020-01-21 12:38 UTC
Since Fedora 31 I've had a reproducible GNOME display window issue, where for Wayland apps when I increase the size of the window past a point relative to the desktop or maximize the window I get very strange display issues with that window.  So far I've seen this happen with gnome-terminal, Image Viewer (eog), Firefox, and others.  With XWayland apps I get a different issue where the application window will occasionally make a sudden white flash and generate a coredump but not crash.

I initially thought this must've been a GNOME 3.34 bug because I never had this problem in Fedora 30 or before.  I opened an issue with GNOME there where you can see more description and screenshots https://gitlab.gnome.org/GNOME/mutter/issues/942

But I discovered if I turn of `Accelerate 3D graphics` for my VM then all the issues go away.  They reproducibly and immediately come back once I turn it back on.  So this is definitely an issue with the VMware graphics driver on Fedora 31.

VMware Workstation Pro 15.5
Windows 10 Pro Host (1909)
Fedora 31 Guest

**Comment by thomashvmw** [comment] 2020-01-21 19:01
Could you post a "dmesg" log from the guest and a host "vmware.log" incorporating a session when this happened?
Thanks,
Thomas

**Comment by hermidalc** [comment] 2020-01-27 16:18
Hi @thomashvmw - when I resize Wayland native apps like e.g. gnome-terminal and Firefox and I see the strange window issues that only happen when Accelerate 3D graphics is enabled but I do not see anything happening in dmesg at that exact time.

Specifically what I've found is that when I resize the width or the height of the Wayland app window to be large enough past a certain threshold of the host desktop width or height then the strange app window display issues start.  The moment I resize it smaller than the threshold it goes away.

I do see vmwgfx command buffer errors in dmesg.  Also the XWayland app I use a lot, Atom, will have these white flashes and not crash but generate a coredump and dmesg.  I'm not sure they are linked because they can happen at different times from each other.

Attached are two [dmesg.log](https://github.com/vmware/open-vm-tools/files/4118019/dmesg.log) [dmesg2.log](https://github.com/vmware/open-vm-tools/files/4118023/dmesg2.log) a relevant [journalctl.log](https://github.com/vmware/open-vm-tools/files/4118027/journalctl.log) and my [vmware.log](https://github.com/vmware/open-vm-tools/files/4118046/vmware.log)

**Comment by hermidalc** [comment] 2020-01-30 17:40
Dear @thomashvmw - here are some screenshots to more clearly see the problem with Accelerate 3D graphics and Fedora 31.  When native Wayland application windows such as gnome-terminal, Firefox, and many others are resized such that the size is bigger than a certain threshold relative to the host desktop size (not guest), then you see these strange display behavior with the edges of the window.

Things are fine when app window size is large compared to guest desktop size but not host desktop size:

<img width="1333" alt="2020-01-30-1" src="https://user-images.githubusercontent.com/461066/73474536-9ee3c180-435c-11ea-8f5b-e627669b111e.png">

Or app window size is small compared to host desktop size:

<img width="1333" alt="2020-01-30-2" src="https://user-images.githubusercontent.com/461066/73474605-bfac1700-435c-11ea-9c1c-a9e8beb8d21e.png">

But the moment you resize it larger beyond a threshold size relative to the host desktop size then:

<img width="1333" alt="2020-01-30-3" src="https://user-images.githubusercontent.com/461066/73474729-f08c4c00-435c-11ea-95e9-a9ad2798d790.png">

Firefox is harder to show a screenshot since it exhibits the same display issue as above losing the with the window edges as you are resizing but when corrects itself once you let go of the mouse.  But if you maximize the window and the un-maximize it you sometimes gets this display issue where the right and bottom parts of the window will suddenly extend beyond the desktop:

<img width="1333" alt="2020-01-30-5" src="https://user-images.githubusercontent.com/461066/73474903-3ea14f80-435d-11ea-92ff-085abdf68b3f.png">

For XWayland apps such as Atom the issue is different when the window is sized large enough it will periodically during use make white flashes and generate a coredump as well as dmesg info.

All of the above behaviors disappear when Accelerate 3D graphics is turned off.  This issue also didn't occur until Fedora 31.

**Comment by jeremyn** [comment] 2020-02-03 15:45
I'm getting a similar problem with Ubuntu:

VMware Workstation Pro 15.5.1 build-15018445
Host: Windows 10 Pro 1909
Guest: Ubuntu 18.04 and 19.10 (and Fedora 31)
"vmware-toolbox-cmd -v" in Ubuntu reports "11.0.1.15528 (build-14773994)"
Host resolution is 4k (3840x2160)

These are in new VMs, installed directly from desktop ISOs, for example "ubuntu-19.10-desktop-amd64.iso" SHA256 hash "96a8095001d447bbb9078925d72f7a77a3f62fbd78460093759af4394ce83d79". 

I noticed this when I maximized Firefox in the guest and starting seeing significant tearing/redraw problems. This only happens with Wayland and with 3D acceleration enabled in VMware. It doesn't happen until I do a full package (apt/dnf) upgrade in the guest.

Similar to how @hermidalc describes it, I can trigger the problem with Firefox by slowly increasing the width and/or height of the application window. The Firefox address bar visibly glitches/moves on Ubuntu when the problem starts. I used the "screenruler" package to see at what pixel count the problem starts and have seen the problem start at different dimensions such as approximately at 2850w by 1450h and 3100w by 1350h. It's interesting that in all cases, the approximate pixel area for the problem is about 4,100,000px which is very close to the area of the default 2560x1600 monitor VMware suggests if you don't choose "Use host setting for monitors".

**Comment by thomashvmw** [comment] 2020-02-03 15:52
I'm currently unable to reproduce at least the Fedora 31 problem here, but OTOH my screen is currently limited to 1600x1200. @jeremyn, what host are you using (Windows / Linux?)

**Comment by thomashvmw** [comment] 2020-02-03 15:53
Ah, never mind, now I see it's Windows.

**Comment by jeremyn** [comment] 2020-02-03 16:04
Yes, Windows host. At the risk of oversimplifying, I think the problem is: VMware + Wayland + 4k + updated packages.

A way to test is to open Firefox, go to Preferences > General, and scroll up and down and move your cursor over parts of the screen. I found the problem much more noticeable on Ubuntu than on Fedora. On Fedora the redraw problems were more subtle, you'd have to scroll up and down and you'd see occasional duplication. On Ubuntu, significant parts of the window become completely garbled. It is immediately noticeable. It's not just Firefox, the file manager and terminal also show the problem.

**Comment by hermidalc** [comment] 2020-02-03 16:07
Yes I have 4k monitor and desktop too.  For me the easiest way to test this is with gnome-terminal if you are in VM guest full screen simply maximize the gnome-terminal issue and you will immediately see the problem.

**Comment by jeremyn** [comment] 2020-02-03 16:12
@hermidalc If I may ask, how are you working around the problem? It's unusable for me as-is. Unfortunately I get some graphical lag when I switch to xorg -- maybe because there is no refresh sync so it renders thousands of FPS -- and, separate problem, for some reason the guest OS doesn't allow me to select a 1920x1080 resolution. There are some random workarounds online to these two problems I haven't tried yet.

**Comment by hermidalc** [comment] 2020-02-03 16:13
@thomashvmw you will also see in the journalctl log I posted that with XWayland app like Atom a few minutes before the Atom window white flashes and gens a coredump I occasionally get an abrt message that the kernel had a problem and in the log you will see it's vmwgfx causing the kernel a command buffer error.  Here is another example [journactl2.log](https://github.com/vmware/open-vm-tools/files/4148847/journactl2.log)

**Comment by hermidalc** [comment] 2020-02-03 16:14
> 
> 
> @hermidalc If I may ask, how are you working around the problem? It's unusable for me as-is. Unfortunately I get some graphical lag when I switch to xorg -- maybe because there is no refresh sync so it renders thousands of FPS -- and, separate problem, for some reason the guest OS doesn't allow me to select a 1920x1080 resolution. There are some random workarounds online to these two problems I haven't tried yet.

Turn off 3D graphics acceleration for your VM.

**Comment by thomashvmw** [comment] 2020-02-03 16:17
@jeremyn, you mention you don't see the problem until you do a full dnf update. Could you try to boot your VM with the old (pre-update) kernel and see if the problem persists. That would help pinpoint what component is at fault.
Thanks, Thomas

**Comment by jeremyn** [comment] 2020-02-03 16:27
@hermidalc Makes sense, I mentioned that my first post in this thread. I've added "3D acceleration" to my little summary above at https://github.com/vmware/open-vm-tools/issues/400#issuecomment-581486759.

**Comment by jeremyn** [comment] 2020-02-03 16:40
@thomashvmw On Fedora 31 both the new kernel 5.4.15 and the old kernel 5.3.7 have the problem. Please note also that I'm seeing this problem on updated Ubuntu 18.04 which is using kernel 4.15.0. I don't think the kernel is particularly relevant here.

**Comment by jeremyn** [comment] 2020-02-03 16:47
More info: On Ubuntu 18.04 I uninstalled the repository-provided open-vm-tools v11.0 and installed v10.3 with "Install VMware Tools..." and that did not fix the problem either.

**Comment by thomashvmw** [comment] 2020-02-03 16:47
@jeremyn, OK, thanks.This sounds like a mesa driver problem then. I'll try to get hold of a monitor with decent resolution.

**Comment by thomashvmw** [comment] 2020-02-03 16:50
@jeremyn, open-vm-tools really has very little to do with vmware graphics except resolution setting. The graphics drivers are shipped with other packages.

**Comment by thomashvmw** [comment] 2020-02-04 14:46
OK, so the window repainting issue is due to a vmware driver bugfix in mesa that uncovers another unanticipated bug. I'll see if I can get a fix in as soon as possible.
Meanwhile, reverting to mesa <= 19.2.2 should help fixing this.

**Comment by hermidalc** [comment] 2020-02-04 16:30
Thank you @thomashvmw for figuring out the source of the issue, much appreciated

**Comment by jeremyn** [comment] 2020-02-04 17:28
Thanks @thomashvmw. I tested in Ubuntu 18.04 by holding (`apt-mark hold`) packages `libegl-mesa0`, `libegl1-mesa`, `libgl1-mesa-dri`, `libgl1-mesa-glx`, `libglapi-mesa`, and `libglx-mesa0` to release version 18.0.5 instead of upgrading to 19.2.8, and then upgrading the rest of the system, and that seems to have avoided the redraw problem. (Downgrading these packages from an already upgraded system seemed trickier because it wanted to uninstall many important other packages, so I didn't go ahead with that.)

**Comment by jeremyn** [comment] 2020-02-14 15:36
@thomashvmw Thanks for your quick research into this problem before. Do you have any general sense of when the bug you mentioned will be fixed in Mesa? Maybe a link to the Mesa bug?

**Comment by thomashvmw** [comment] 2020-02-17 13:01
The fix is now part of mesa master, mesa 20.0.0-rc3 and 19.3.4.
I'm not sure if affected distros (like Fedora 31) will switch from mesa 19.2 to 19.3, since it looks like mesa 19.2 has reached EOL.

**Comment by thomashvmw** [comment] 2020-02-18 14:11
I've filed bugs for Ubuntu and Fedora to either switch to mesa 19.3 or cherry-pick the bugfix.
https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1863763
https://bugzilla.redhat.com/show_bug.cgi?id=1803819

**Comment by hermidalc** [comment] 2020-02-24 16:27
Thanks very much @thomashvmw.

**Comment by stanguturi** [comment] 2020-04-09 18:49
> I've filed bugs for Ubuntu and Fedora to either switch to mesa 19.3 or cherry-pick the bugfix.
> https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1863763
> https://bugzilla.redhat.com/show_bug.cgi?id=1803819

Thanks @thomashvmw The bugs logged above should fix the issue. Closing.

**Closed by stanguturi** 2020-04-09 18:49 UTC
