### ISSUE TITLE
No USB devices in Kubuntu 22.10 guest

### ISSUE THREAD

**Issue by HautDam** [vmware/open-vm-tools#633] opened 2023-01-08 19:56 UTC
### Describe the bug

No USB devices can be connected to Kubuntu  guest. 

Setup details:
- Win10 host running Workstation 16.2.4 Player.
- New, up-to-date install of Kubuntu 22.10 guest.
- open-vm-tools and open-vm-tools-desktop installed and up-to-date.

### Reproduction steps

1. Run the VM.
2. Run `vmware-user` in Konsole due to bug #629.
3. Try to connect any USB device from vmware command bar. None can. 
4. Plug in a USB and wait for the vmware dialog that asks whether to connect the device to the host or guest. You can select the K22.10 guest, but it fails to connect.

### Expected behavior

USB device connects to guest.

**Comment by pengzhencao** [comment] 2023-01-10 08:16
Let me try if I could reproduce it locally.  
Please attach the guest's /var/log/syslog when you do the usb connection.

**Comment by HautDam** [comment] 2023-01-12 06:24
It doesn't generate _any_ new messages in syslog.

**Comment by gauravjvmw** [comment] 2023-01-12 06:32
Can you please attach the vmx file of guest OS for which usb detection is not working?

**Comment by HautDam** [comment] 2023-01-12 15:04
[Kubuntu 22.10.vmx.txt](https://github.com/vmware/open-vm-tools/files/10402960/Kubuntu.22.10.vmx.txt)

Here you go.

**Comment by gauravjvmw** [comment] 2023-01-12 15:17
Okay i found what i am looking for,   can you please set this usb.restrictions.defaultAllow = "TRUE" in vmx file? 
This should ideally fix your problem. Unfortunately we are seeing users reporting this issue in WS 16.2.x but we are unable to repro this internally. 

If this fixes your issue, can you please help me with more details so that we can root cause it. 
- Win10 host version, 
- open-vm-tools version and 
- Is this fresh new VM? Can you please trying another new VM any linux flavour ? 
And if you see same problem there also.
- what all you do from creating this new VM and till the point where you faced this issue, anything interesting you did we should know?
- any specific usb device you were trying to connect. 
- Kubuntu 22.10 iso link.
- Also if possible can you please try this on WS 17.0 Player.

**Comment by pengzhencao** [comment] 2023-01-12 18:44
I've set up a fresh installed kubuntu 22.10 VM with vmplayer 16.2.4 on a windows 10 host. 
USB Disk works  fine after changing USB compatibility to USB 3.1 in the VM's settings. However, I've checked your VM's vmx config file and  you've already enabled the usb3.1(xhci) so this might not be the root cause.

I do not have the "usb.restrictions.defaultAllow = FALSE" with my vmx config. So maybe you could try what gauravjvmw suggested to change that option to "TRUE" or just remove that line from the vmx config. Then power on the VM and connect usb again.

Besides the questions gauravjvmw asked, please also share the "vmware*.log" in the VM's folder on the host and the "/var/log/syslog" on the guest with us to help debug the issue.

**Comment by HautDam** [comment] 2023-01-13 06:59
Changing usb.restrictions.defaultAllow to TRUE **fixed** the problem! Yay!

To answer your questions:
- Windows is Win10 Pro, 20H2
- open-vm-tools* is 12.1.0-1
- Other Linux: I installed Kubuntu 22.04. Worked flawlessly. I did the upgrade to 22.10 and the problem came back. Same behavior as if I had install 22.10 afresh. No auto-run of vmware-user and no USB.
- The VM never crashed. 
- At the time I was trying to connect a portable drive, but I tried with a joystick, a 3D mouse, and card reader.
- ISO link: https://cdimage.ubuntu.com/kubuntu/releases/22.10/release/kubuntu-22.10-desktop-amd64.iso
- I would be willing to try with WS 17, but it's just not possible.

Which set of logs would you like? When that setting is false, and causing problems, or when it's true and things are fine?

Thank you for the support!

**Comment by gauravjvmw** [comment] 2023-01-13 07:17
Good to know that fixed your problem.  Please setup a new Guest VM on which you did repro this issue and then simply power on the VM and do whatever you are doing and see if it repros the issue. 
After that i would need Logs present at "vmware*.log" + vmx file in the VM's folder and ui logs. 
For UI log, go to location mentioned in Help Menu -> About VMware Player >> Notice UI Log file text.
Just zip whatever logs you have there in that location.

**Comment by pengzhencao** [comment] 2023-01-13 16:01
I've find  a way to repro this with my own env.

* Create a ubuntu-64bit VM in the VM player, follow the GUI wizard but before click the "Finish" button, choose "customize hardware" button, then in the pop up GUI, change the usb controller type from usb2.0(ehci) to usb3.1(xhci). Then click finish.
* Then in the generated vmx file, there is the "usb.restrictions.defaultAllow = FALSE" option set, which will causing guest usb connection failure.

We have an internal bug to track this issue. Before it is resolved please use the workaround suggested by gauravjvmw. Anyway, this should be issue with workstation/player GUI rather than open-vm-tools.

**Comment by HautDam** [comment] 2023-01-13 18:34
Done, and behaving as before. Zipped logs are attached. 
Thanks again for sharing the workarounds.

[K2210_logs.zip](https://github.com/vmware/open-vm-tools/files/10414418/K2210_logs.zip)

**Comment by gauravjvmw** [comment] 2023-01-13 20:00
Thanks @HautDam . Appreciate all your help. I think we are good to close this issue from open-vm-tools. 
It's anyways WS issue and now we are tracking it.

**Comment by johnwvmw** [comment] 2023-01-13 20:22
The issue is being tracked by the Workstation/Player product team.  This is not an open-vm-tools issue; closing the issue.

@HautDam, thanks for bring the problem to our attention.

**Closed by johnwvmw** 2023-01-13 20:22 UTC
Labels: bug
