### ISSUE TITLE
Customization command failed: Failed to connect to bus: Broken pipe

### ISSUE THREAD

**Issue by jmgilman** [vmware/open-vm-tools#517] opened 2021-06-04 22:54 UTC
**OS**: Ubuntu 20.04
**VMTools**: 11.2.5
**vCenter**: 7.0.2 

Cloning a fully updated Ubuntu 20.04 image with guest customization using the vSphere Terraform provider is producing the following error:

```
[2021-06-04T22:19:38.637Z] [   error] Customization command failed with exitcode: 1, stderr: 'Failed to connect to bus: Broken pipe
Failed to open initctl fifo: No such device or address
Failed to talk to init daemon.
'.
```

The base image has cloud-init completely removed (`apt purge cloud-init`) in order to force Perl customization. The customization process seems to be working as expected as the hostname and all networking gets set correctly. However, the problem is that due to the log indicating a failure, Terraform is subsequently complaining that guest customization failed and is marking all the VMs as tainted. 

All of my searching has only led me to kb's that were only applicable to older versions of the customization tool, so I'm not sure what the solution here is. 

[Here is the full log.](https://gist.github.com/jmgilman/6da1b49289fc945071779b6680fb1a8c)

**Comment by PengpengSun** [comment] 2021-09-15 03:48
Hi @jmgilman,

This is a known issue and has been fixed in VMTools 11.3.0. The error is due to customization repeatedly executes '/sbin/telinit' command to reboot vm, the command could fail with exitcode:1 and stderr since rebooting is ongoing and init daemon has been stopped.
In VMTools 11.3.0, it detects such failure and then log [info] but [error]. As you noticed, customization still works well with this error,

**Comment by xiaofengw-vmware** [comment] 2021-09-15 03:49
This is a known issue and it is fixed on end of Jan, 2021. Please upgrade the VMTools to 11.3.0. Thanks.

**Comment by PengpengSun** [comment] 2021-09-15 07:13
And according to https://bugs.launchpad.net/ubuntu/+source/open-vm-tools/+bug/1933143, VMTools 11.3.0 has entered focal-proposed repository, you can try to upgrade VMTools to 11.3.0 after [EnableProposed](https://wiki.ubuntu.com/Testing/EnableProposed)

**Comment by stanguturi** [comment] 2021-09-15 18:32
> However, the problem is that due to the log indicating a failure, Terraform is subsequently complaining that guest customization failed and is marking all the VMs as tainted.

@jmgilman The log message was incorrectly tagged as the 'error' instead of 'info'. Are we sure that terraform is tagging the operation as failed because 'error' string appeared in the log file? Is Terraform really parsing the log file instead of just relying on the exit code? Anyway, please check @PengpengSun comments.

> This is a known issue and has been fixed in VMTools 11.3.0. The error is due to customization repeatedly executes '/sbin/telinit' command to reboot vm, the command could fail with exitcode:1 and stderr since rebooting is ongoing and init daemon has been stopped.
> In VMTools 11.3.0, it detects such failure and then log [info] but [error]. As you noticed, customization still works well with this error,

Thanks @PengpengSun . This issue was fixed in 4a9cdfb5190706a8471bf668247011a0725af09c Please update to the latest tools. Closing this issue.

Please reopen if the issue is still reproducible with the latest tools.

**Closed by stanguturi** 2021-09-15 18:32 UTC

**Comment by zjokhio** [comment] 2023-06-18 13:10
I am facing the same issue with vmware tools version **12.1.0.37487**

**Comment by PengpengSun** [comment] 2023-06-18 13:49
@zjokhio would you please share the /var/log/vmware-imc/toolDeployPkg.log from the vm you are seeing this issue.
