### ISSUE TITLE
vmsvc[4535]: [ warning] [vmsvc] SOCKET failed to create socket, error 97: Address family not supported by protocol 

### ISSUE THREAD

**Issue by andyshamu** [vmware/open-vm-tools#163] opened 2017-05-22 09:20 UTC
Hello Team,

We are receving multiple alerts for few of the serverscan you please suggest.

vmsvc[4535]: [ warning] [vmsvc] SOCKET failed to create socket, error 97: Address family not supported by protocol vmsvc[4535]: [ warning] [vmsvc] SOCKET failed to create socket, error 97: Address family not supported by protocol vmsvc[4535]: [ warning] [vmsvc] SOCKET failed to create socket, error 97: Address family not supported by protocol vmsvc[4535]: [ warning] [vmsvc] SOCKET failed to create socket, error 97: Address family not supported by protocol vmsvc[4535]: [ warning] [vmsvc] SOCKET failed to create socket, error 97: Address family not supported by protocol vmsvc[4535]: [ warning] [vmsvc] SOCKET failed to create socket, error 97: Address family not supported by protocol vmsvc[4535]: [ warning] [vmsvc] SOCKET failed to create socket, error 97: Address family not supported by protocol vmsvc[4535]: [ warning] [vmsvc] SOCKET failed to create socket, error 97: Address family not supported by protocol 

Regards,
Anand

**Comment by epavser** [comment] 2017-07-18 07:13
Hi,

I have the same issue. Any chances that you have solved it?

BR,
Pavel

**Comment by epavser** [comment] 2017-07-18 11:22
The following kernel configs were missing:
VSOCKETS
VMWARE_VMCI_VSOCKETS
VMWARE_VMCI

**Comment by oliverkurth** [comment] 2017-07-19 19:46
Sorry for coming to this late, but it looks like @epavser found the solution.

The issue is most likely caused by the vmw_vmci and vsock modules not being loaded (check with `lsmod`). Please make sure that both are loaded with:

```
sudo modprobe -v vmw_vmci
sudo modprobe -v vmci

```
Although this should happen automatically. If thse modules are missing and you are using a custom built  kernel, make sure that these are enabled, see @evparser 's comment.

If this doesn't help, please send the version of open-vm-tools and the OS with version that you are using.

**Comment by stanguturi** [comment] 2019-07-05 20:42
The solutions provided in the previous comment should work. Closing.

**Closed by stanguturi** 2019-07-05 20:42 UTC
