### ISSUE TITLE
Ubuntu 20.04 Guest customization failed for network config

### ISSUE THREAD

**Issue by arogarth** [vmware/open-vm-tools#453] opened 2020-08-03 09:02 UTC
Hello,

build our Ubuntu images for 18.04 and 20.04. Both has the same setup - blank installed ubuntu from seed with same packages installed.

After deploy the template Ubuntu 18.04  the open-vm-tools are successfully created the netplan configs and apply them to the system.
On Ubuntu 20.04 - this is not happened. Always the file /etc/network/interfaces is created - but without the correct interface name... Just "ether" is set as name - not ens192 or so...

Both Template has netplan.io installed and work without cloud-init....

**Comment by PengpengSun** [comment] 2020-08-04 01:34
Hi @arogarth, may I know your vCenter server version? and /var/log/vmware-imc/toolsDeployPkg.log on Ubuntu20.04 VM is helpful for locating the root cause.

**Comment by arogarth** [comment] 2020-08-04 03:50
Hey, we have vCenter 7.0 (latest update), vCloud 10.1 (latest).
[toolsDeployPkg.log](https://github.com/vmware/open-vm-tools/files/5019986/toolsDeployPkg.log)

**Comment by arogarth** [comment] 2020-08-04 03:52
What I cannot understand is the way to detect the Interfaces - Ubuntu 18.04 uses `ip`and ts fine, in Ubuntu 20.04 the script uses `ifconfig` - Both has installed net-tools package and the `ip` command is also available....

**Comment by PengpengSun** [comment] 2020-08-04 05:20
This is a vCloud 10.1 known issue, as far as I know, vCloud team is fixing this issue right now. For the reason of in Ubuntu 20.04 uses `ifconfig`, it's due to vCloud 10.1 does NOT have the perl script which supports Ubuntu 20.04 customization, so it's using the general perl script for Ubuntu distro. 
See "INFO: Detected distribution: Ubuntu Linux Distribution" in toolsDeployPkg.log, this means general perl script for Ubuntu distro was using, the correct info should be "INFO: Detected distribution: Ubuntu 20.04", it will use `ip`.

**Comment by arogarth** [comment] 2020-08-04 06:20
Ah, thanks! Is there a workaround or KB from VMware?? Because also cloud-init did not work - it lost the static ip after reboot....

**Comment by PengpengSun** [comment] 2020-08-04 08:27
Hi, Here is temp workaround which you can modify /etc/issue file of Ubuntu20.04 VM, change it as below:
```
$cat /etc/issue
Ubuntu 18.04 \n \l
```

**Comment by arogarth** [comment] 2020-08-04 08:36
hmm... ok, this is not very nice to populate such image templates as a provider to customers...

I used this: https://kb.vmware.com/s/article/71264

**Comment by PengpengSun** [comment] 2020-08-04 08:50
Nice, the kb is for cloud-init customization. That should work fine with Ubuntu 20.04 Server image. If you are using Ubuntu 20.04 Live Server image, please remove file /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg if it exists before cloud-init customization.

**Comment by PengpengSun** [comment] 2020-10-27 02:20
FYI:
vCloud 10.1.2 supports Ubuntu 20.04 customization. See https://docs.vmware.com/en/VMware-Cloud-Director/10.1/rn/VMware-Cloud-Director-1012-Release-Notes.html

**Comment by stanguturi** [comment] 2021-02-09 05:51
> FYI:
> vCloud 10.1.2 supports Ubuntu 20.04 customization. See https://docs.vmware.com/en/VMware-Cloud-Director/10.1/rn/VMware-Cloud-Director-1012-Release-Notes.html

Thanks @PengpengSun The issue should be fixed in vCloud 10.1.2 Please reopen the issue if the issue is still reproducible with the latest version.

**Closed by stanguturi** 2021-02-09 05:51 UTC
