### ISSUE TITLE
Guest customization not working in Ubuntu 20.04

### ISSUE THREAD

**Issue by andrewmooreio** [vmware/open-vm-tools#483] opened 2020-11-19 20:24 UTC
I'm trying to create an Ubuntu 20.04 template to be used as a clone source, and I'm having issues trying to get guest customization with cloud-init to work.

- vCenter 7.0 Update 1 (16858589)
- ESXi 7.0.1 Update 1 (16850804)
- VMware Tools 11.1.5.22735 (16724464)
- cloud-init 20.3-2-g371b392c-0ubuntu1~20.04.1

The source template is built from the Ubuntu 20.04.1 live server ISO, with very few changes made. Fresh install then the following steps were performed:

1. Added _disable_vmware_customization: false_ to _/etc/cloud/cloud.cfg_
2. rm -rf /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
3. rm -rf /etc/cloud/cloud.cfg.d/99-installer.cfg
4. apt update && apt dist-upgrade -y
5. poweroff

Per https://kb.vmware.com/s/article/59557 and https://kb.vmware.com/s/article/80934.

Issue a) When cloning the source template, the network adapter on the clone will always be disconnected. Despite it being connected in the source, and "Connect At Power On" checked. I have checked this countless times and never seen the issue with any other OS. I've even tried creating a brand new template, to see if it was a one-off, with no luck.

Issue b) I manually connect the network and power on. I get "Started customization of VM..." in the event log as expected. I wait a while and I see "An error occured while customizing VM..." a few moments later.

The following is the output from cloud-init: 

https://0bin.net/paste/nzlujvx6#YcsxFF2YSF75agWZn9WDFr6Yeum9EsxWUDL1q8fh52T

The following is the output from VMware Tools:

https://0bin.net/paste/rmSYAIPU#6yk6Lr55m+S-O8qov0Ho6sDbgWS4A3j85o4Nf+/L6in

Any help would be greatly appreciated, it worked a treat with vCenter 6.7 U3g. Thanks in advance.

**Comment by PengpengSun** [comment] 2020-11-20 01:24
Hi @andrewmooreio 

For issue a), it's expected since customization task will always disconnect cloned VM NICs and if everything works fine after powered-on, cloud-init will reconnect the NICs back.

According to the output from cloud-init, datasourceOVF failed to get data which it should do.

> 2020-10-30 18:14:22,207 - util.py[WARNING]: Getting data from <class 'cloudinit.sources.DataSourceOVF.DataSourceOVF'> failed

I think the steps you made on source template are correct. Let's check the full /var/log/cloud-init.log to get why DataSoureOVF failed to get data, you can run 'cloud-init collect-logs' to collect the logs. https://cloudinit.readthedocs.io/en/latest/topics/cli.html?highlight=collect-logs#collect-logs

**Comment by andrewmooreio** [comment] 2020-11-23 08:42
Hi @PengpengSun, thanks a lot for your reply. Please see attached for the cloud-init logs.
[cloud-init.tar.gz](https://github.com/vmware/open-vm-tools/files/5581736/cloud-init.tar.gz)

**Comment by PengpengSun** [comment] 2020-11-23 10:23
Hi @andrewmooreio 

Thanks for the logs. From the cloud-init.log, it showed customization script is included in the customization specification. 

> 2020-11-19 20:27:34,020 - config_file.py[DEBUG]: FOUND CATEGORY = 'MISC'
> 2020-11-19 20:27:34,020 - config_file.py[DEBUG]: ADDED KEY-VAL :: 'MISC|MARKER-ID' = '5238ff46-ef09-6945-6749-8b216aa76ad7'
> 2020-11-19 20:27:34,020 - config_file.py[DEBUG]: FOUND CATEGORY = 'CUSTOM-SCRIPT'
> 2020-11-19 20:27:34,020 - config_file.py[DEBUG]: ADDED KEY-VAL :: 'CUSTOM-SCRIPT|SCRIPT-NAME' = 'script.bat'

But by default, the enable-custom-scripts option is disabled in Tools configuration, so the DatasourceOVF threw an exception:

> 2020-11-19 20:27:34,034 - util.py[DEBUG]: Getting data from <class 'cloudinit.sources.DataSourceOVF.DataSourceOVF'> failed
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 770, in find_source
>     if s.update_metadata([EventType.BOOT_NEW_INSTANCE]):
>   File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 659, in update_metadata
>     result = self.get_data()
>   File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 278, in get_data
>     return_value = self._get_data()
>   File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceOVF.py", line 185, in _get_data
>     _raise_error_status(
>   File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceOVF.py", line 682, in _raise_error_status
>     raise error
>   File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceOVF.py", line 179, in _get_data
>     raise RuntimeError(msg)
> RuntimeError: Custom script is disabled by VM Administrator

Please turn on the enable-custom-scripts option in the source template follow this KB and try again.
https://kb.vmware.com/s/article/74880

**Comment by andrewmooreio** [comment] 2020-11-23 11:34
I have made the change as suggested, but customization still fails.

`vmware-toolbox-cmd config set deployPkg enable-custom-scripts true`

[cloud-init_2.tar.gz](https://github.com/vmware/open-vm-tools/files/5582628/cloud-init_2.tar.gz)

**Comment by PengpengSun** [comment] 2020-11-23 12:05
Please double-check the customization script, cloud-init failed due to Syntax error in the script.

> 2020-11-23 11:29:12,211 - DataSourceOVF.py[DEBUG]: Error executing pre-customization script: Unexpected error while running command.
> Command: ['/root/.customization/customize.sh', 'precustomization']
> Exit code: 2
> Reason: -
> Stdout: 
> Stderr: /root/.customization/customize.sh: 5: Syntax error: "elif" unexpected

**Comment by andrewmooreio** [comment] 2020-11-23 13:27
Thanks @PengpengSun, I've removed any customization scripts to simplify troubleshooting.

The initial customization now succeeds, however when the VM is rebooted cloud-init fails again.

[cloud-init_3.tar.gz](https://github.com/vmware/open-vm-tools/files/5583227/cloud-init_3.tar.gz)

**Comment by PengpengSun** [comment] 2020-11-23 13:56
Hi @andrewmooreio 

> The initial customization now succeeds, however when the VM is rebooted cloud-init fails again.

When there was customization happening, cloud-init loaded data through DatasourceOVF correctly. Then when the VM rebooted, there was no data to load through DatasourceOVF, so cloud-init went through the rest Datasources in datasource list to try to load data.  You can see the datasource list by 'cat /etc/cloud/cloud.cfg.d/90_dpkg.cfg'.
An error happened at DataSourceRbxCloud, I did NOT see this error before, but as a workaround, you can reconfigure the Datasource list of cloud-init by running 'dpkg-reconfigure cloud-init' and selecting OVF only.

> 2020-11-23 13:22:24,273 - util.py[DEBUG]: Getting data from <class 'cloudinit.sources.DataSourceRbxCloud.DataSourceRbxCloud'> failed
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 770, in find_source
>     if s.update_metadata([EventType.BOOT_NEW_INSTANCE]):
>   File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 659, in update_metadata
>     result = self.get_data()
>   File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 278, in get_data
>     return_value = self._get_data()
>   File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceRbxCloud.py", line 226, in _get_data
>     self.userdata_raw = rbx_data['userdata']
> TypeError: 'bool' object is not subscriptable

For above error, I will try to reproduce it locally and report it to cloud-init team.

**Comment by andrewmooreio** [comment] 2020-11-23 14:04
Thank you @PengpengSun, I really appreciate your assistance.

I guess we can resolve this issue, as those errors are not related to open-vm-tools or VMware.

**Comment by PengpengSun** [comment] 2020-11-23 14:09
@andrewmooreio You are welcome, we will close this issue.

**Closed** 2020-11-23 18:26 UTC
