### ISSUE TITLE
Guest customization script not working on RHEL8

### ISSUE THREAD

**Issue by gorantornqvist** [vmware/open-vm-tools#471] opened 2020-10-09 13:58 UTC
Hi,
We are using guest customization on RHEL8 and configuring ipadress, hostname, etc works fine.
However running a customization script doesnt and Im not sure how to troubleshoot this.

Our vmware infra guys are saying that they added this script:
```
#!/bin/sh
echo "$(date) - $1" >>/tmp/customization.log
```
According to https://kb.vmware.com/s/article/74880

We are then deploying a new VM using vRA. But the /tmp/customization.log file is not created in the deployed VM.

If I check the toolsDeployPkg.log file I can see this:
```
2020-10-09T11:23:28 INFO: Reads value of the deployPkg enable-custom-scripts 
2020-10-09T11:23:28 DEBUG: Command: 'vmware-toolbox-cmd config get "deployPkg"  "enable-custom-scripts" 2>/tmp/guest.customization.stderr' 
2020-10-09T11:23:28 DEBUG: Exit Code: 0 
2020-10-09T11:23:28 DEBUG: Result: [deployPkg] enable-custom-scripts = true
 
2020-10-09T11:23:28 DEBUG: Stderr:  
2020-10-09T11:23:28 INFO: Marker file exists or is undefined, pre-customization is not needed

2020-10-09T11:23:29 INFO: Marker file exists or is undefined, password settings are not needed
2020-10-09T11:23:29 INFO: Marker file exists or is undefined, post-customization is not needed
```
How can I verify that the customization script set in vmware is passed correctly to vmware tools?
Any suggestion how to troubleshoot?

open-vm-tools-11.0.0-4.el8.x86_64

Thanks ...

**Comment by ravindravmw** [comment] 2020-10-11 23:37
@gorantornqvist Thanks for reporting this issue. It seems like a duplicate of https://github.com/vmware/open-vm-tools/issues/470? FYI, I have notified the concerned developers to get back on this.

**Closed by ravindravmw** 2020-10-11 23:37 UTC
