### ISSUE TITLE
open-vm-tools not functionnal

### ISSUE THREAD

**Issue by ThinkAndAdvance** [vmware/open-vm-tools#535] opened 2021-08-01 16:44 UTC
Hi 
excuse my poor english :)
My config Ubuntu 21.04, fresh installed.
I installed open-vm-tools and rebooted but also the service is well running, I just can't use drag'n'drop from/to Ubuntu's VM, nor enable a share to my Windows 10 Host : 

"....systemctl status open-vm-tools
● open-vm-tools.service - Service for virtual machines hosted on VMware
     Loaded: loaded (/lib/systemd/system/open-vm-tools.service; enabled; vendor>
     Active: active (running) since Sun 2021-08-01 01:37:24 CEST; 8min ago"
Not any error occured during the installation.

I don't have any /var/log/vmware-vmsvc.log, but vmware-vmsvc-root.log

My package version : 
vmtoolsd -v
VMware Tools daemon, version 11.2.5.26209 (build-17337674)

Process in memory : 
ps awx | grep vmtoolsd
    702 ?        Ssl    1:55 /usr/bin/vmtoolsd
  47305 pts/1    S+     0:00 grep --color=auto vmtoolsd

Thanx for any assistance :)
Cheers

**Comment by ThinkAndAdvance** [comment] 2021-08-10 17:23
anyone to help ? :)

**Comment by lemke1458** [comment] 2021-08-10 18:06
Canonical ships the desktop parts of open-vmtools (which covers drag & drop) in the open-vmtools-desktop package; have you installed that?

**Comment by ThinkAndAdvance** [comment] 2021-08-10 18:28
Hello 
Thanl you for helping @lemke1458 
no, I thought installing Open vm tools, all the different options will be installed too (i am a Microsoft experienced user, so usually in Microsoft + Vmware world, all is installed at the same time)
How can i install this desktop part ?

**Comment by ThinkAndAdvance** [comment] 2021-08-10 18:30
anyway, it is not my only pb ... the cursor is not working fine, as it is not pointing exactly but aside what i want to clic :(

**Comment by johnwvmw** [comment] 2021-08-10 18:47
You have only mentioned the installation and running of the open-vm-tools package.   The Drag n Drop feature requires additional vmtools plugins and services that are contained in the open-vm-tools-desktop package.

As user root on the UB system, install the open-vm-tools-desktop package.

   ` apt-get install open-vm-tools-desktop`

Log off of the desktop and log back in.   Before entering your password, check that you are using an X1`1/Xorg based graphical client - not Wayland.   There is a setting drop-down menu on the password screen.

After logging in to the desktop, run
   `ps -ef | grep tools`

There should be 2 vmtoolsd processes running - one running as "root" is the open-vm-tools system process.  The second should be the desktop user that just logged in.

      `/usr/bin/vmtoolsd -n vmusr --blockFd 3`

You DnD functionality should be working.

**Comment by ThinkAndAdvance** [comment] 2021-08-10 22:21
hey 
my DND works fine :)

My Sharing too, i found the way to enable it (... each time i have to type the command, but it is ok)

last 2 thing : 
- enable to use the RESTART/SUSPEND button from VMWARE Player console : I found nothg on Google :(
- enable touchpad on the UBUNTU 21.04 VM : the same, nothg talk about the VM, but about the UBUNTU as a Host

xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
**⎜   ↳ VMware VMware Virtual USB Mouse         	id=7	[slave  pointer  (2)]
⎜   ↳ VirtualPS/2 VMware VMMouse              	id=9	[slave  pointer  (2)]
⎜   ↳ VirtualPS/2 VMware VMMouse              	id=10	[slave  pointer  (2)]**
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=8	[slave  keyboard (3)]

and 

cat /proc/bus/input/devices
...
I: Bus=0003 Vendor=0e0f Product=0003 Version=0110
N: Name="VMware VMware Virtual USB Mouse"
P: Phys=usb-0000:02:00.0-1/input0
S: Sysfs=/devices/pci0000:00/0000:00:11.0/0000:02:00.0/usb2/2-1/2-1:1.0/0003:0E0F:0003.0001/input/input3
U: Uniq=
H: Handlers=mouse0 event2 
B: PROP=0
B: EV=17
B: KEY=ff0000 0 0 0 0
B: REL=903
B: MSC=10

I: Bus=0011 Vendor=0002 Product=0013 Version=0006
N: Name="VirtualPS/2 VMware VMMouse"
P: Phys=isa0060/serio1/input1
S: Sysfs=/devices/platform/i8042/serio1/input/input5
U: Uniq=
H: Handlers=mouse1 event3 
B: PROP=0
B: EV=b
B: KEY=70000 0 0 0 0
B: ABS=3

I: Bus=0011 Vendor=0002 Product=0013 Version=0006
N: Name="VirtualPS/2 VMware VMMouse"
P: Phys=isa0060/serio1/input0
S: Sysfs=/devices/platform/i8042/serio1/input/input4
U: Uniq=
H: Handlers=mouse2 event4 
B: PROP=1
B: EV=7
B: KEY=30000 0 0 0 0
B: REL=103

I think that the missing "synaptic touchpad" is the explanation of non working on the VM Guest.

From my Windows Host, here is the driver : Synaptics Pointing Device

thanx :)

**Comment by johnwvmw** [comment] 2021-08-10 23:32
You can make your "shared folders" automatic at boot/reboot, follow the steps in [KB 74650](https://kb.vmware.com/s/article/74650).

It is not clear what you mean by "enable ... RESTART/SUSPEND buttons".   Here is a link to the current Player User Doc (https://docs.vmware.com/en/VMware-Workstation-Player-for-Windows/index.html) which contains a section on Suspend and Resume.

**Comment by ThinkAndAdvance** [comment] 2021-08-11 06:14
> You can make your "shared folders" automatic at boot/reboot, follow the steps in [KB 74650](https://kb.vmware.com/s/article/74650).
> 
> It is not clear what you mean by "enable ... RESTART/SUSPEND buttons". Here is a link to the current Player User Doc (https://docs.vmware.com/en/VMware-Workstation-Player-for-Windows/index.html) which contains a section on Suspend and Resume.

Hi
What happens is that whenever I want to restart/suspend/stop the VM respectively using the buttons from the VMware player menu, it says that it just can't work on Linux guest.
I know this is working fine talking about Microsoft guest.

**Comment by johnwvmw** [comment] 2021-08-12 23:15
I have installed Ubuntu 21.04 desktop on a VMware Player 16.1.2.  The open-vm-tools and open-vm-tools-desktop version 11.2.5 were installed as part of the installation process.

The Shutdown, Suspend, Restart, and Power On buttons work as expected.  I cannot reproduce the problems that you are seeing - no "can't work on Linux guest"

**Comment by ThinkAndAdvance** [comment] 2021-08-14 08:23
> I have installed Ubuntu 21.04 desktop on a VMware Player 16.1.2. The open-vm-tools and open-vm-tools-desktop version 11.2.5 were installed as part of the installation process.
> 
> The Shutdown, Suspend, Restart, and Power On buttons work as expected. I cannot reproduce the problems that you are seeing - no "can't work on Linux guest"

Hello @johnwvmw 
Indeed, now I am able to use it (suspend, start) but it just still remain this error : 
![Capture](https://user-images.githubusercontent.com/88284185/129439804-8429b81c-dd1e-4b6e-890f-ddf6fd1e1c03.PNG)

I think it could be because they were already part of vmware files in my distro too, and to delete/reinstall all should correct it.

Last but not least, how can I use the touchpad in the Host (Synaptic) but it does not work to scroll : I just can move the cursor, not scroll.

On Google, it seems no solution really to fix it, though it is a material compatibility declaration matter.

Have you any idea ? :)

Cheers

**Comment by johnwvmw** [comment] 2021-08-17 16:16
The connection of the Synaptic touchpad is really not a function of open-vm-tools.

AFAIK, at the moment, there's no way to connect a Synaptic touchpad directly to the guest, or get that functionality working within the Linux guest.  These issues are handled on the host side.

I suggest that you raise the touchpad query with a wider group at the VMware Technology Network - https://communities.vmware.com/ .  The Desktop Hypervisor community seems like the best choice.

**Comment by ThinkAndAdvance** [comment] 2021-08-17 21:09
> The connection of the Synaptic touchpad is really not a function of open-vm-tools.
> 
> AFAIK, at the moment, there's no way to connect a Synaptic touchpad directly to the guest, or get that functionality working within the Linux guest. These issues are handled on the host side.
> 
> I suggest that you raise the touchpad query with a wider group at the VMware Technology Network - https://communities.vmware.com/ . The Desktop Hypervisor community seems like the best choice.

ok
anyway, U were a huge help i can assume that ;)

C u

**Comment by stanguturi** [comment] 2021-09-13 21:31
Closing this issue as per the comments in https://github.com/vmware/open-vm-tools/issues/535#issuecomment-900437340 and https://github.com/vmware/open-vm-tools/issues/535#issuecomment-900632073

**Closed by stanguturi** 2021-09-13 21:31 UTC
