### ISSUE TITLE
GIMP over Fedora 31 running in Vmware, generate artifacts

### ISSUE THREAD

**Issue by nulltypifier** [vmware/open-vm-tools#412] opened 2020-03-16 22:48 UTC
Hi.

I am running GIMP 2.10.14 on Fedora 31.

Fedora 31 runs on Vmware Workstation 15.5.2 on Windows 10, when I enable 3D acceleration, GIMP produces artifacts as the screenshot shows.

By disabling 3D acceleration, the problem disappears, but GIMP performance is significantly reduced.

Apologies: I'm not sure if this entry corresponds to open-vm-tools. However I think open-vm-tools handles acceleration in Fedora within the VM.

Greeting.

![captura de pantalla de 2020-03-16 18-06-32](https://user-images.githubusercontent.com/57726043/76805832-acdf8b80-67be-11ea-889c-f36f317a955d.png)
![captura de pantalla de 2020-03-16 19-41-46](https://user-images.githubusercontent.com/57726043/76805837-b1a43f80-67be-11ea-9f3b-ddc9e8baef71.png)

**Comment by jenerdba** [comment] 2020-03-18 19:56
Hi,

I'm experiencing similar issue with Oracle's SQL Developer tool when using Gnome/Wayland. The screen paints find in Gnome/Xorg.
![Linux-2020-03-18-15-54-37](https://user-images.githubusercontent.com/11458168/77001901-0d8ed580-6931-11ea-8436-a93228353719.png)

**Comment by thomashvmw** [comment] 2020-03-18 21:14
I think this is a dupe of #400, which has a solution. But you need to bug your favourite distro to incorporate the solution.

/Thomas

**Comment by stanguturi** [comment] 2020-04-09 18:47
> I think this is a dupe of #400, which has a solution. But you need to bug your favourite distro to incorporate the solution.

Thanks Thomas. This is a duplicate of #400. Closing.

**Closed by stanguturi** 2020-04-09 18:47 UTC
