### ISSUE TITLE
VMware tools reports Installed but not running for ubuntu guest.

### ISSUE THREAD

**Issue by asamuthi** [vmware/open-vm-tools#327] opened 2019-03-21 05:52 UTC
ESXi version: 6.5
Host version: Ubuntu 16.04
Open-vm-tools version: VMware Tools daemon, version 10.3.5.7752 (build-10430147)

Every few days the vmware tools reports Installed but not running for the ubuntu guest.

Work around: Restart the process or the system.

**Comment by stanguturi** [comment] 2019-03-21 19:28
> Every few days the vmware tools reports Installed but not running for the ubuntu guest.
Are you referring to the running status in the Management UI for the VM? When this happens, is there is a valid tools process running inside the guest?

Can you please provide the logs for tools service available at /var/log/vmware*.log?

**Comment by asamuthi** [comment] 2019-03-25 04:51
Yes I am referring to the running status in the Management UI.

Please find some logs attached.
Mar 03 09:42:37.114] [ message] [vmtoolsd] Plugin 'vmbackup' initialized.
[Mar 03 09:43:00.930] [ message] [vix] VixTools_ProcessVixCommand: command 62
[Mar 11 19:13:50.138] [ message] [vmsvc] Log caching is enabled with maxCacheEntries=4096.
[Mar 11 19:13:50.181] [ message] [vmsvc] Core dump limit set to -1
[Mar 11 19:13:50.424] [ message] [vmsvc] Log caching is enabled with maxCacheEntries=4096.
[Mar 11 19:13:50.425] [ message] [vmsvc] Core dump limit set to -1
[Mar 11 19:13:50.425] [ message] [vmtoolsd] Tools Version: 10.0.7.52125 (build-3227872)
[Mar 11 19:13:50.464] [ message] [vmsvc] Cannot load message catalog for domain 'hgfsServer', language 'C', catalog dir '/usr/share/open-vm-tools'.
[Mar 11 19:13:50.464] [ message] [vmtoolsd] Plugin 'hgfsServer' initialized.
[Mar 11 19:13:50.464] [ message] [vmsvc] Cannot load message catalog for domain 'vix', language 'C', catalog dir '/usr/share/open-vm-tools'.
[Mar 11 19:13:50.464] [ message] [vmtoolsd] Plugin 'vix' initialized.
[Mar 11 19:13:50.464] [ message] [vmsvc] Cannot load message catalog for domain 'deployPkg', language 'C', catalog dir '/usr/share/open-vm-tools'.
[Mar 11 19:13:50.464] [ message] [vmtoolsd] Plugin 'deployPkg' initialized.
[Mar 11 19:13:50.465] [ message] [vmsvc] Cannot load message catalog for domain 'grabbitmqProxy', language 'C', catalog dir '/usr/share/open-vm-tools'.
[Mar 11 19:13:50.465] [ message] [vmtoolsd] Plugin 'grabbitmqProxy' initialized.
[Mar 11 19:13:50.465] [ message] [vmsvc] Cannot load message catalog for domain 'guestInfo', language 'C', catalog dir '/usr/share/open-vm-tools'.
[Mar 11 19:13:50.465] [ message] [vmtoolsd] Plugin 'guestInfo' initialized.
[Mar 11 19:13:50.465] [ message] [vmsvc] Cannot load message catalog for domain 'powerops', language 'C', catalog dir '/usr/share/open-vm-tools'.
[Mar 11 19:13:50.465] [ message] [vmtoolsd] Plugin 'powerops' initialized.
[Mar 11 19:13:50.465] [ message] [vmsvc] Cannot load message catalog for domain 'timeSync', language 'C', catalog dir '/usr/share/open-vm-tools'.
[Mar 11 19:13:50.465] [ message] [vmtoolsd] Plugin 'timeSync' initialized.
[Mar 11 19:13:50.466] [ message] [vmsvc] Cannot load message catalog for domain 'vmbackup', language 'C', catalog dir '/usr/share/open-vm-tools'.
[Mar 11 19:13:50.466] [ message] [vmtoolsd] Plugin 'vmbackup' initialized.
[Mar 11 19:14:13.983] [ message] [vix] VixTools_ProcessVixCommand: command 62
[Mar 16 16:55:07.535] [ warning] [vmsvc] SimpleSock: Send error for socket 9: 32[Broken pipe]
{code}

**Comment by stanguturi** [comment] 2019-03-25 19:02
> Yes I am referring to the running status in the Management UI.

Thanks for the snippet. 

> [Mar 11 19:14:13.983] [ message] [vix] VixTools_ProcessVixCommand: command 62
> [Mar 16 16:55:07.535] [ warning] [vmsvc] SimpleSock: Send error for socket 9: 32[Broken pipe]

There was a socket error. I think, the communication between the ESX and vmtoolsd (in guest) was broken and hypervisor thought that tools service was not running. We need some more information (log files) to figure out what is happening. Please send vmware.log from ESXi and tools log bundle (/var/log/vm*log). These files might contain sensitive information, so please send them to my email address: stanguturi@vmware.com Will request you if any other information is required.

Also, did you build the open-vm-tools by yourself or are you using the default bundled distro version?

**Comment by asamuthi** [comment] 2019-03-26 05:00
Not sure if this will help .
Logs from ESXi host:

019-03-14T12:03:04.445Z| vmx| I125: TOOLS state change 3 returned status 1
2019-03-14T12:03:04.445Z| vmx| I125: Vix: [101183 mainDispatch.c:4151]: VMAutomationReportPowerStateChange: Reporting power state change (opcode=2, err=0).
2019-03-14T12:03:04.445Z| vmx| I125: Tools: Changing running status: 2 => 1.
2019-03-14T12:03:06.614Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-14T12:03:08.627Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-14T12:04:09.682Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-14T12:05:10.585Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-14T12:06:10.577Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-14T12:08:10.724Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-14T12:09:11.577Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-14T12:10:11.579Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-14T12:11:11.574Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-14T12:12:11.663Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-14T12:13:12.597Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-14T12:14:13.510Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-14T12:15:13.589Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-14T12:16:14.333Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-14T12:17:15.592Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-14T12:18:15.590Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
2019-03-15T01:37:57.035Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:37:59.099Z| vcpu-0| I125: Tools: Tools heartbeat timeout.
2019-03-15T01:37:59.099Z| vcpu-0| I125: Tools: Running status rpc handler: 1 => 0.
2019-03-15T01:37:59.099Z| vcpu-0| I125: Tools: Changing running status: 1 => 0.
2019-03-15T01:38:17.039Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:38:37.043Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:38:57.048Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:39:17.053Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:39:37.059Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:39:57.063Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:40:17.068Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:40:37.073Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:40:57.078Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:41:17.083Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:41:37.087Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:41:57.093Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:42:17.097Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:42:37.101Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:42:57.106Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:43:17.112Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:43:37.115Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
2019-03-15T01:43:57.119Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.

**Comment by asamuthi** [comment] 2019-03-26 05:45
We are using a bundled distro version.

**Comment by stanguturi** [comment] 2019-03-26 21:55
Thanks for providing the ESX log file for the VM.

>2019-03-14T12:18:15.590Z| svga| I125: MKSScreenShotMgr: Taking a screenshot
>2019-03-15T01:37:57.035Z| vmx| I125: GuestRpcSendTimedOut: message to toolbox timed out.
>2019-03-15T01:37:59.099Z| vcpu-0| I125: Tools: Tools heartbeat timeout.

As seen above, a message to the tools service timed out and hypervisor tagged the tools as 'not running'. Do you have the logs for 'tools' from inside the guest during that timeframe?

If you don't have that info, you can try the following:
* Configure the debug logging for the tools and leave the VM. More instructions for configuring tools debug logging are available at https://kb.vmware.com/s/article/1007873
* When this issue happens again, you can capture the log bundle from inside the guest and provide us.

**Comment by asamuthi** [comment] 2019-04-09 15:53
I have emailed you the debug logs as requested. Please take a look. Let me know anything I can do to get the fix ASAP.

**Comment by stanguturi** [comment] 2019-04-29 22:13
> I have emailed you the debug logs as requested. Please take a look. Let me know anything I can do to get the fix ASAP.

Thanks for the sending the log bundle. Since you have already created a support request with VMware, let's use that channel for further communication.

**Comment by stanguturi** [comment] 2019-05-14 18:53
> Thanks for the sending the log bundle. Since you have already created a support request with VMware, let's use that channel for further communication.

I was able to reproduce the issue internally using the following steps:

* Installed Ubuntu 16.04.6 Server 32-bit in a VM. (Install from ubuntu-16.04.6-server-i386.iso available at http://releases.ubuntu.com/16.04/)
* Configured the VM with only 1GB of RAM and 1CPU.
* By default open-vm-tools 10.2.0 is available in the Ubuntu VM.
* After a few hours (it took around 7 hours 30 minutes for my test), the tools running status was changed to 'not running' in the UI.

After investigation, found that this is due to a bug (fixed in latest linux kernel release) in the upstreamed vsock driver. It was fixed in https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f42a0fd13bd281811e7457b28d939c8e8b808868
which is available in Linux kernel 4.6

Note that this issue could be reproduced only when the VM is configured with 1vCPU. With 2vCPU,  there is no issue. To resolve the issue, you can configure the VM with 2 vCPUs or update the Linux kernel to the latest version (atleast 4.6). Closing this issue.

Thanks
Sankar.

**Closed by stanguturi** 2019-05-14 18:53 UTC
