### ISSUE TITLE
vmtoolsd memory leak

### ISSUE THREAD

**Issue by anan-dahadha** [vmware/open-vm-tools#514] opened 2021-05-06 13:20 UTC
This issue is specific to the software vmtoolsd software running on CentOS cluster

After 76 days of uptime , the cluster showed vmtoolsd using 1.6GB of memory (RES value from top) , and usage for this service was steadily increasing. This made it the third largest memory consumer on the.

Timing and size of memory usage incrementation doesn't show a pattern so far, but usage did not ever decrease. individual increases were around 60 to 120 KiB at a time.

This issue started occurring from version open-vm-tools-11.0.5-3.el7_9.1.

checked with sudo /usr/bin/vmware-toolbox-cmd -v and we see version is 11.0.5.17716

**Comment by jonathanvmw** [comment] 2021-05-06 18:20
@anan-dahadha

What host (including version) is this running on?

What version of CentOS are you using?

Was a different version of tools running on this system previously, and if so, what?

Does the file /etc/vmware-tools/tools.conf exist on the system?  If so, can you provide a copy?

Thanks.

**Comment by MalkmusT** [comment] 2021-05-21 08:01
I can confirm this issue one my machines, where vmtoolsd use up to 75% of memory dependent on system runtime.


In the following an example of an Centos 7 vm that was up for 66 days
```
uptime
 09:53:54 up 66 days, 18:21,  1 user,  load average: 0.01, 0.07, 0.12
```

```
yum list open-vm-tools
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.fau.de
 * epel: epel.mirror.omnilance.com
 * extras: centos.mirror.iphh.net
 * updates: centos.bio.lmu.de
Installed Packages
open-vm-tools.x86_64                                              11.0.5-3.el7_9.1                                               @updates
Available Packages
open-vm-tools.x86_64                                              11.0.5-3.el7_9.3                                               updates
```

```
ps aux | grep vmtoolsd
root        849  0.0 25.3 4403140 4110820 ?     Ssl  Mar15  55:46 /usr/bin/vmtoolsd
```

```
uname -a
Linux Server 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
vmtoolsd --version
VMware Tools daemon, version 11.0.5.17716 (build-15389592)
```

@jonathanvmw  i will see if your suggestion imporves the situation, atm there is no file `/etc/vmware-tools/tools.conf`
I guess this will be solved as sone as the new version will make it into the update packages.

**Comment by jonathanvmw** [comment] 2021-06-07 16:13
@anan-dahadha 
@MalkmusT 

Have you tried the suggested change to tools.conf?  Did it make a difference?

Thanks.

**Comment by anan-dahadha** [comment] 2021-06-08 12:05
@jonathanvmw, I have updated our setup with the latest open-vm rpm version, and the issue is not seen. 

Thanks.

**Comment by jonathanvmw** [comment] 2021-06-08 12:07
@anan-dahadha - Thanks for the update.  Glad to hear it's working.

**Comment by MalkmusT** [comment] 2021-06-10 13:02
@jonathanvmw 

unfortunately the settings change did not resolve the issue for me:
```
root     120943  0.0  5.8 1217668 947124 ?      Ssl  May26  14:37 /usr/bin/vmtoolsd
```

i will try to update the system to the latest rpm version.

**Comment by johnwvmw** [comment] 2021-07-06 16:38
@MalkmusT 

Just a followup, the config changes to tools.conf will not recover the memory already leaded.  It is expected to "stop" the leak.   To recover to lost memory, you will need to restart the vmtoolsd service.

**Comment by stanguturi** [comment] 2021-09-13 21:36
> @anan-dahadha - Thanks for the update. Glad to hear it's working.

Thanks @jonathanvmw and @anan-dahadha Closing this issue since it's resolved.

**Closed by stanguturi** 2021-09-13 21:36 UTC
