### ISSUE TITLE
Fedora 28: runProgramInGuest failed with SELinux enabled

### ISSUE THREAD

**Issue by deepak-rawat** [vmware/open-vm-tools#329] opened 2019-03-22 20:11 UTC
vmtoolsd user process will crash as a result and once I disable SELinux things work fine.

```
Mar 22 12:42:53 localhost.localdomain audit[1180]: USER_AUTH pid=1180 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:vmtools_t:s0 msg='op=PAM:authentication grantors=pam_shells,pam_unix acct="drawat" exe="/usr/bin/vmtoolsd" hostname=? addr=? terminal=? res=success'
Mar 22 12:42:53 localhost.localdomain audit[1180]: USER_ACCT pid=1180 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:vmtools_t:s0 msg='op=PAM:accounting grantors=pam_shells,pam_unix acct="drawat" exe="/usr/bin/vmtoolsd" hostname=? addr=? terminal=? res=success'
Mar 22 12:42:53 localhost.localdomain audit[1180]: CRED_ACQ pid=1180 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:vmtools_t:s0 msg='op=PAM:setcred grantors=pam_shells,pam_unix acct="drawat" exe="/usr/bin/vmtoolsd" hostname=? addr=? terminal=? res=success'
Mar 22 12:42:53 localhost.localdomain VGAuth[1180]: vmtoolsd: Username and password successfully validated for 'drawat'.
Mar 22 12:42:53 localhost.localdomain audit[1180]: USER_AUTH pid=1180 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:vmtools_t:s0 msg='op=PAM:authentication grantors=pam_shells,pam_unix acct="drawat" exe="/usr/bin/vmtoolsd" hostname=? addr=? terminal=? res=success'
Mar 22 12:42:53 localhost.localdomain audit[1180]: USER_ACCT pid=1180 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:vmtools_t:s0 msg='op=PAM:accounting grantors=pam_shells,pam_unix acct="drawat" exe="/usr/bin/vmtoolsd" hostname=? addr=? terminal=? res=success'
Mar 22 12:42:53 localhost.localdomain audit[1180]: CRED_ACQ pid=1180 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:vmtools_t:s0 msg='op=PAM:setcred grantors=pam_shells,pam_unix acct="drawat" exe="/usr/bin/vmtoolsd" hostname=? addr=? terminal=? res=success'
Mar 22 12:42:53 localhost.localdomain VGAuth[1180]: vmtoolsd: Username and password successfully validated for 'drawat'.
Mar 22 12:42:53 localhost.localdomain audit: SELINUX_ERR op=security_compute_sid invalid_context=unconfined_u:unconfined_r:vmtools_unconfined_t:s0-s0:c0.c1023 scontext=unconfined_u:unconfined_r:vmtools_t:s0-s0:c0.c1023 tcontext=system_u:object_r:shell_exec_t:s0 tclass=process
Mar 22 12:42:53 localhost.localdomain vmusr[2774]: [2019-03-22T19:42:53.521Z] [   error] [vmusr] Unable to execute the ""/usr/bin/perl" "/home/drawat/src/mtt/setup-linux.pl" "--resultsDir" "/home/drawat/tmp" "--postBootSetup" "--timeout" "731" " shell command: Permission denied.
Mar 22 12:42:53 localhost.localdomain audit[2774]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 subj=unconfined_u:unconfined_r:vmtools_t:s0-s0:c0.c1023 pid=2774 comm="vmtoolsd" exe="/usr/bin/vmtoolsd" sig=6 res=1
Mar 22 12:42:53 localhost.localdomain systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Mar 22 12:42:53 localhost.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@0-2775-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 22 12:42:53 localhost.localdomain systemd[1]: Started Process Core Dump (PID 2775/UID 0).
Mar 22 12:42:54 localhost.localdomain systemd-coredump[2776]: Process 2774 (vmtoolsd) of user 1000 dumped core.
                                                              
                                                              Stack trace of thread 2774:
                                                              #0  0x00007fe85741153f raise (libc.so.6)
                                                              #1  0x00007fe8573fb895 abort (libc.so.6)
                                                              #2  0x00007fe859ced775 n/a (libvmtools.so.0)
                                                              #3  0x00007fe859cf0b40 n/a (libvmtools.so.0)
                                                              #4  0x00007fe8597684ff g_logv (libglib-2.0.so.0)
                                                              #5  0x00007fe8597686f3 g_log (libglib-2.0.so.0)
                                                              #6  0x00007fe859cf18aa Panic (libvmtools.so.0)
                                                              #7  0x00007fe859d12a59 n/a (libvmtools.so.0)
                                                              #8  0x00007fe859d13684 ProcMgr_ExecAsync (libvmtools.so.0)
                                                              #9  0x00007fe849860072 n/a (libvix.so)
                                                              #10 0x00007fe849862620 n/a (libvix.so)
                                                              #11 0x00007fe8498660ed n/a (libvix.so)
                                                              #12 0x00007fe84985f09b n/a (libvix.so)
                                                              #13 0x00007fe859d14bc4 RpcChannel_Dispatch (libvmtools.so.0)
                                                              #14 0x00007fe859d1679e n/a (libvmtools.so.0)
                                                              #15 0x00007fe859d1706c n/a (libvmtools.so.0)
                                                              #16 0x00007fe85976106d g_main_context_dispatch (libglib-2.0.so.0)
                                                              #17 0x00007fe859761438 n/a (libglib-2.0.so.0)
                                                              #18 0x00007fe859761762 g_main_loop_run (libglib-2.0.so.0)
                                                              #19 0x000055af1fc392be n/a (vmtoolsd)
                                                              #20 0x000055af1fc385e7 main (vmtoolsd)
                                                              #21 0x00007fe8573fd413 __libc_start_main (libc.so.6)
                                                              #22 0x000055af1fc386be _start (vmtoolsd)
Mar 22 12:42:54 localhost.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@0-2775-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 22 12:42:56 localhost.localdomain abrt-notification[2824]: Process 2774 (vmtoolsd) crashed in ??()
Mar 22 12:43:01 localhost.localdomain dbus-daemon[1755]: [session uid=1000 pid=1755] Activating via systemd: service name='org.gtk.vfs.Metadata' unit='gvfs-metadata.service' requested by ':1.13' (uid=1000 pid=1834 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Mar 22 12:43:01 localhost.localdomain systemd[1720]: Starting Virtual filesystem metadata service...
Mar 22 12:43:01 localhost.localdomain dbus-daemon[1755]: [session uid=1000 pid=1755] Successfully activated service 'org.gtk.vfs.Metadata'
Mar 22 12:43:01 localhost.localdomain systemd[1720]: Started Virtual filesystem metadata service.
Mar 22 12:43:04 localhost.localdomain org.freedesktop.problems.applet[1755]: /usr/bin/gnome-abrt:331: DeprecationWarning: Gtk.Application.add_accelerator is deprecated
Mar 22 12:43:04 localhost.localdomain org.freedesktop.problems.applet[1755]:   self.add_accelerator("<Control>q", "app.quit")

```

**Comment by stanguturi** [comment] 2019-03-25 17:48
> vmtoolsd user process will crash as a result and once I disable SELinux things work fine.

What is the version of tools installed in the VM?

**Comment by deepak-rawat** [comment] 2019-03-25 18:25
vmtoolsd --version
VMware Tools daemon, version 10.3.10.10540 (build-12406962)

**Comment by stanguturi** [comment] 2019-03-25 18:45
> vmtoolsd --version
> VMware Tools daemon, version 10.3.10.10540 (build-12406962)

Thanks, Deepak for the update.

> Mar 22 12:42:53 localhost.localdomain audit: SELINUX_ERR op=security_compute_sid invalid_context=unconfined_u:unconfined_r:vmtools_unconfined_t:s0-s0:c0.c1023 scontext=unconfined_u:unconfined_r:vmtools_t:s0-s0:c0.c1023 tcontext=system_u:object_r:shell_exec_t:s0 tclass=process
Mar 22 12:42:53 localhost.localdomain vmusr[2774]: [2019-03-22T19:42:53.521Z] [   error] [vmusr] Unable to execute the ""/usr/bin/perl" "/home/drawat/src/mtt/setup-linux.pl" "--resultsDir" "/home/drawat/tmp" "--postBootSetup" "--timeout" "731" " shell command: Permission denied.

From the log files, there was a permission issue while starting the '/usr/bin/perl'. From "VMware Tools" perspective, a proper attempt was made to start the program. But the SELinux was blocking the perl script. What exactly is done by the setup-linux.pl? Does it do any network configuration which is not allowed? Did you face the crash if any other program like 'bin/sh' / etc is executed?

Few things to try out:
* https://fedoraproject.org/wiki/SELinux/audit2allow
Please use this tool to scan the log messages and generate a policy which could have worked.

* https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security-enhanced_linux/sect-Security-Enhanced_Linux-Fixing_Problems-Allowing_Access_audit2allow

Can you try out 'audit2allow -w -a' and see if any useful meaningful information is available about the error.

**Comment by deepak-rawat** [comment] 2019-03-25 18:57
@stanguturi Thanks Sankar for your analysis. Actually the perl script does some setup needed for automated testing and that include some root privilege tasks, setting resolution, etc. I can look more into SELinux permission for that perl script. In any case I think vmtoolsd process should not crash. 

I will test with some other program which does not require root privilege later. Thanks.

**Comment by deepak-rawat** [comment] 2019-04-02 18:50
@stanguturi 

Hi executing a simple bash script which only do echo "Hello world" or simply executing "/usr/bin/ls" also result in same "Permission denied." error. Although it didn't caused vmtoolsd to crash.

```
Apr 02 11:47:39 localhost.localdomain audit[1141]: CRED_ACQ pid=1141 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:vmtools_t:s0 msg='op=PAM:setcred grantors=pam_shells,pam_unix acct="drawat" exe="/usr/bin/vmtoolsd" hostname=? addr=? terminal=? res=success'
Apr 02 11:47:39 localhost.localdomain VGAuth[1141]: vmtoolsd: Username and password successfully validated for 'drawat'.
Apr 02 11:47:39 localhost.localdomain audit[2744]: AVC avc:  denied  { entrypoint } for  pid=2744 comm="vmtoolsd" path="/usr/bin/bash" dev="dm-0" ino=2883877 scontext=system_u:system_r:vmtools_unconfined_t:s0 tcontext=system_u:object_r:shell_exec_t:s0 tclass=file permissive=0
Apr 02 11:47:39 localhost.localdomain VGAuth[2744]: [2019-04-02T18:47:39.203Z] [   error] [vmsvc] Unable to execute the ""/usr/bin/bash" "/home/drawat/src/mtt/test.sh" " shell command: Permission denied.
Apr 02 11:47:39 localhost.localdomain audit[2744]: ANOM_ABEND auid=4294967295 uid=1000 gid=1000 ses=4294967295 subj=system_u:system_r:vmtools_t:s0 pid=2744 comm="vmtoolsd" exe="/usr/bin/vmtoolsd" sig=6 res=1
Apr 02 11:48:32 localhost.localdomain audit[1141]: USER_AUTH pid=1141 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:vmtools_t:s0 msg='op=PAM:authentication grantors=pam_shells,pam_unix acct="drawat" exe="/usr/bin/vmtoolsd" hostname=? addr=? terminal=? res=success'
Apr 02 11:48:32 localhost.localdomain audit[1141]: USER_ACCT pid=1141 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:vmtools_t:s0 msg='op=PAM:accounting grantors=pam_shells,pam_unix acct="drawat" exe="/usr/bin/vmtoolsd" hostname=? addr=? terminal=? res=success'
Apr 02 11:48:32 localhost.localdomain audit[1141]: CRED_ACQ pid=1141 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:vmtools_t:s0 msg='op=PAM:setcred grantors=pam_shells,pam_unix acct="drawat" exe="/usr/bin/vmtoolsd" hostname=? addr=? terminal=? res=success'
Apr 02 11:48:32 localhost.localdomain VGAuth[1141]: vmtoolsd: Username and password successfully validated for 'drawat'.
Apr 02 11:48:32 localhost.localdomain audit[1141]: USER_AUTH pid=1141 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:vmtools_t:s0 msg='op=PAM:authentication grantors=pam_shells,pam_unix acct="drawat" exe="/usr/bin/vmtoolsd" hostname=? addr=? terminal=? res=success'
Apr 02 11:48:32 localhost.localdomain audit[1141]: USER_ACCT pid=1141 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:vmtools_t:s0 msg='op=PAM:accounting grantors=pam_shells,pam_unix acct="drawat" exe="/usr/bin/vmtoolsd" hostname=? addr=? terminal=? res=success'
Apr 02 11:48:32 localhost.localdomain audit[1141]: CRED_ACQ pid=1141 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:vmtools_t:s0 msg='op=PAM:setcred grantors=pam_shells,pam_unix acct="drawat" exe="/usr/bin/vmtoolsd" hostname=? addr=? terminal=? res=success'
Apr 02 11:48:32 localhost.localdomain VGAuth[1141]: vmtoolsd: Username and password successfully validated for 'drawat'.
Apr 02 11:48:32 localhost.localdomain audit[2791]: AVC avc:  denied  { entrypoint } for  pid=2791 comm="vmtoolsd" path="/usr/bin/bash" dev="dm-0" ino=2883877 scontext=system_u:system_r:vmtools_unconfined_t:s0 tcontext=system_u:object_r:shell_exec_t:s0 tclass=file permissive=0
Apr 02 11:48:32 localhost.localdomain VGAuth[2791]: [2019-04-02T18:48:32.975Z] [   error] [vmsvc] Unable to execute the ""/usr/bin/ls"" shell command: Permission denied.
Apr 02 11:48:32 localhost.localdomain audit[2791]: ANOM_ABEND auid=4294967295 uid=1000 gid=1000 ses=4294967295 subj=system_u:system_r:vmtools_t:s0 pid=2791 comm="vmtoolsd" exe="/usr/bin/vmtoolsd" sig=6 res=1
Apr 02 11:48:38 localhost.localdomain org.gnome.Shell.desktop[1810]: Window manager warning: last_user_time (2013768) is greater than comparison timestamp (2013737).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Apr 02 11:48:38 localhost.localdomain org.gnome.Shell.desktop[1810]: Window manager warning: W1 (drawat@loc) appears to be one of the offending windows with a timestamp of 2013768.  Working around...

```

**Comment by stanguturi** [comment] 2019-04-03 19:57
> Hi executing a simple bash script which only do echo "Hello world" or simply executing "/usr/bin/ls" also result in same "Permission denied." error. Although it didn't caused vmtoolsd to crash.

Thanks for trying out this test. So, this is not something special related to 'perl' permissions / etc. Any generic 'start program' command fails due to 'permission errors'.

Did you install the official VMware Tools from ISO? or
Are you using the bundled distro version of tools? or
Did you build the tools from source and install in the guest?

As I have requested in an earlier comment, 

> https://fedoraproject.org/wiki/SELinux/audit2allow
> Please use this tool to scan the log messages and generate a policy which could have worked.

> https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security-enhanced_linux/sect-Security-Enhanced_Linux-Fixing_Problems-Allowing_Access_audit2allow

Can you please use the tool to generate a policy that could have worked?

**Comment by stanguturi** [comment] 2019-04-04 20:49
I have installed a new 'Fedora 29 workstation 64-bit' VM in my ESX machine and reproduced the issue. I followed these instructions as mentioned in https://fedoraproject.org/wiki/SELinux/audit2allow:

$ cat /var/log/audit/audit.log | audit2allow -m local > local.te
$ cat local.te
module local 1.0;

require {
	type session_dbusd_tmp_t;
	type init_t;
	type vmtools_unconfined_t;
	type shell_exec_t;
	class file entrypoint;
	class dir read;
}

#============= init_t ==============
allow init_t session_dbusd_tmp_t:dir read;

#============= vmtools_unconfined_t ==============
allow vmtools_unconfined_t shell_exec_t:file entrypoint;


$ checkmodule -M -m -o local.mod local.te
$ semodule_package -o local.pp -m local.mod
$ semodule -i local.pp

After this, the startprogram guest operation commands (via vmtoolsd) worked without any issues. Note that I have used the default upstreamed version of open-vm-tools in the fedora VM. So, this seems to be something that fedora-maintainers need to address for the vmtoolsd service.

**Comment by deepak-rawat** [comment] 2019-04-04 22:01
@stanguturi Sorry for not replying to your earlier comment. I was also using default upstreamed version of open-vm-tools in the fedora VM.

Thanks for your analysis, we can close this if this is distro specific.

Deepak

**Comment by stanguturi** [comment] 2019-05-14 18:41
> @stanguturi Sorry for not replying to your earlier comment. I was also using default upstreamed version of open-vm-tools in the fedora VM.

You can uninstall the default upstreamed version of open-vm-tools and install the official tar tools. 
(https://my.vmware.com/web/vmware/details?downloadGroup=VMTOOLS10310&productId=491)

With that, there shouldn't be any issues.

> Thanks for your analysis, we can close this if this is distro specific.

I have logged an internal tracking bug to follow up with fedora maintainers. Closing this bug.

Thanks
Sankar.

**Closed by stanguturi** 2019-05-14 18:41 UTC
