### ISSUE TITLE
Open VMware Tools version 10.2.0.1608 reports randomly wrong IP for Diego Cell used for containerisation with Pivotal PAS. 

### ISSUE THREAD

**Issue by stefanstamov** [vmware/open-vm-tools#373] opened 2019-10-01 08:46 UTC
Hello Team,

We have found that VCenter reports wrong IP address for the Diego cells as it is picking up randomly any of the interfaces of the cell instead of eth0. eth0 is the VM/Cells interface while the other interfaces belong to containers within the cell. This leads to issue where the Diego Cell IP is not shown correctly or cannot be found by searching in VCenter. 

Details:

version 10.2.0.1608
reproduced with vSphere 6.7

There are some extra interfaces from ip command like "s-010255187186@if1380" with IP " 169.254.0.1"

`diego_cell/cb1f5a0f-2626-4f50-b08e-22feef9a40c4:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 169.254.0.2/32 scope global lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:ac:35:bc brd ff:ff:ff:ff:ff:ff
    inet 10.193.78.19/24 brd 10.193.78.255 scope global eth0
       valid_lft forever preferred_lft forever
3: silk-vtep: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether ee:ee:0a:ff:bb:00 brd ff:ff:ff:ff:ff:ff
    inet 10.255.187.0/16 scope link silk-vtep
       valid_lft forever preferred_lft forever
21: s-010255187010@if20: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1404 qdisc noqueue state UP group default
    link/ether aa:aa:0a:ff:bb:0a brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 169.254.0.1 peer 10.255.187.10/32 scope link s-010255187010
       valid_lft forever preferred_lft forever
1381: s-010255187186@if1380: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1404 qdisc noqueue state UP group default
    link/ether aa:aa:0a:ff:bb:ba brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet 169.254.0.1 peer 10.255.187.186/32 scope link s-010255187186
       valid_lft forever preferred_lft forever`

While the IP address of the Cell is as per bellow:

`diego_cell/cb1f5a0f-2626-4f50-b08e-22feef9a40c4:/var/log# cat /etc/network/interfaces
 Generated by bosh-agent
auto lo
iface lo inet loopback
auto eth0
iface eth0 inet static
    address 10.193.78.19
    network 10.193.78.0
    netmask 255.255.255.0
    broadcast 10.193.78.255
    gateway 10.193.78.1`

Open VMware tool is reporting the same IP “ 169.254.0.1” that is showing in vSphere GUI for this specific Diego cell instead of 10.193.78.19 which is wrong.

`diego_cell/cb1f5a0f-2626-4f50-b08e-22feef9a40c4:~$ /usr/bin/vmtoolsd -v
VMware Tools daemon, version 10.2.0.1608 (build-7253323)
diego_cell/cb1f5a0f-2626-4f50-b08e-22feef9a40c4:~$ /usr/bin/vmtoolsd --cmd "info-get guestinfo.ip"
169.254.0.1`

Information on how the network stack is set up can be found here : https://github.com/cloudfoundry/silk

Stefan

**Comment by dsouders** [comment] 2019-10-02 15:47
Thank you for your report.  An internal bug has been filed to investigate this issue.

**Comment by stefanstamov** [comment] 2019-10-02 15:49
@dsouders Thanks for picking this up , Please keep me posted as I have end customer and our R&D team waiting on the resolution of this. 

Stefan

**Comment by oliverkurth** [comment] 2019-10-02 18:09
This is not a bug. open-vm-tools is reporting all IP addresses. I untangled the `ip addr` output:

```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
 inet 127.0.0.1/8 scope host lo
  valid_lft forever preferred_lft forever
 inet 169.254.0.2/32 scope global lo
  valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
 link/ether 00:50:56:ac:35:bc brd ff:ff:ff:ff:ff:ff
 inet 10.193.78.19/24 brd 10.193.78.255 scope global eth0
 valid_lft forever preferred_lft forever
3: silk-vtep: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
 link/ether ee:ee:0a:ff:bb:00 brd ff:ff:ff:ff:ff:ff
 inet 10.255.187.0/16 scope link silk-vtep valid_lft forever preferred_lft forever
21: s-010255187010@if20: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1404 qdisc noqueue state UP group default
 link/ether aa:aa:0a:ff:bb:0a brd ff:ff:ff:ff:ff:ff link-netnsid 0
 inet 169.254.0.1 peer 10.255.187.10/32 scope link s-010255187010
 valid_lft forever preferred_lft forever
1381: s-010255187186@if1380: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1404 qdisc noqueue state UP group default
 link/ether aa:aa:0a:ff:bb:ba brd ff:ff:ff:ff:ff:ff link-netnsid 1
 inet 169.254.0.1 peer 10.255.187.186/32 scope link s-010255187186
valid_lft forever preferred_lft forever
```
Unless configured, the primary address reported is indeed random - there is no way for tools to know which is the 'primary' address. But it can be configured, see https://docs.vmware.com/en/VMware-Tools/11.0.0/com.vmware.vsphere.vmwaretools.doc/GUID-ECCF9D01-3666-40CE-B9FD-7EE0738AB5D9.html (doc is for 11.0, but the feature is in 10.2.0 already).

So I suggest to set something like the following in `/etc/vmware-tools/tools.conf:`

```
[guestinfo]
exclude-nics=s-*
primary-nics=eth0
```

**Comment by stefanstamov** [comment] 2019-10-03 07:24
Thanks @oliverkurth , 

I have forwarded your feedback to our developers, they should be able to integrate this in our stem cell templates. 

Thank you again. 

Stefan

**Comment by oliverkurth** [comment] 2019-10-07 17:59
HI @stefanstamov , do you have any feedback?

**Comment by stefanstamov** [comment] 2019-10-08 08:02
@oliverkurth I am still waiting for our developers but I think it is all clear. I have modified the file as advised in lab and it shows correctly in VC post that. Thank you for your help!

Stefan

**Comment by oliverkurth** [comment] 2019-10-08 18:05
Thanks @stefanstamov , I will close this issue for now. Feel free to reopen if this is still a problem.

**Closed by oliverkurth** 2019-10-08 18:05 UTC
