### ISSUE TITLE
Ubuntu 18.04 doesn't scan new scsi disk

### ISSUE THREAD

**Issue by zyxep** [vmware/open-vm-tools#419] opened 2020-04-19 19:05 UTC
Hi,

We are currently on a vSphere 6.7 with many ubuntu VM's deployed.
After upgrading our vm's to ubuntu 18.04 have we discovered that new disks aren't automatically added to the VM's when we add new ones.

We are on 11.0.1 of open-vm-tools, we need to echo - - - to /sys/class/scasi_host/hostX/scan to find it.
My colleague has also found the tools `scsitools sg3-utils` and then use `rescan-scsi-bus` to find new disk, but I believe this must be a bug in open-vm-tools.
The kernel we are using is 4.15.0-91-generic

**Comment by dsouders** [comment] 2020-04-20 14:19
@zyxep 

What is the most recent Ubuntu version that works?
Is the VM powered off or are you doing hot-add?
Can you enable debug-level Tools logging?
To enable logging see: https://kb.vmware.com/s/article/1007873

**Comment by zyxep** [comment] 2020-04-20 14:29
It works on our 16.04 with hot-add. but hot-add doesn't work on 18.04.
We can't turn off our VM's since they are in production.

**Comment by dsouders** [comment] 2020-04-20 15:31
@zyxep 

Thanks!
Just FYI - There's no need to shut down the VM while enabling/disabling logging.
What scsi controller are you using?

**Comment by zyxep** [comment] 2020-04-20 17:43
I might need help to find out what scsi controller the VM's has.

**Comment by dsouders** [comment] 2020-04-20 18:17
I don't have the UI in front of me right now, but it should be listed somewhere in VM Properties.
If you don't see it there, check the vmx file for the VM.

**Comment by dsouders** [comment] 2020-04-20 20:43
@zyxep 

A local expert has informed me that open-vm-tools is not involved with auto scanning of scsi disks.
What he suspects is that you have something in your VM that uses the "rescan-scsi-bus" script in the optional "scsitools" package, and that upgrading Ubuntu has introduced a new version of the script which now requires additional "-a" and "-r" options to add and remove disks.

The issue is discussed here: https://access.redhat.com/solutions/1314183

Could you please check your VM to confirm?

Thanks!

**Comment by zyxep** [comment] 2020-04-21 11:08
I just tried with sg3-utils & scsitools on our ubuntu 18.04 it doesn't find new disks automatic.
it finds it when I run the command `rescan-scsi-bus.sh -a` i'm just still curious why it won't do it automatic.

**Comment by dsouders** [comment] 2020-04-21 14:37
I think you first need to understand what was running on your 16.04 VM to automatically re-scan because updating to 18.04 has broken it.
My guess would be you have a script that periodically runs rescan-scsi-bus.sh and it needs to be updated with the new "-a" arg, but that's purely a guess.
There might be some clues in the kernel logs.

**Comment by vasartori** [comment] 2020-12-08 20:49
same issue here... any help?

**Comment by zyxep** [comment] 2020-12-08 20:52
> same issue here... any help?

I found our problem actually, it was because we didn't use Paravirtual SCSI controller for our VM's.
So double check that on your vm's and if that is the case, shutdown the VM's change it to Paravirtual & boot it up again.
+ remember do spawn your template as a VM and change it and convert it back to a template (if that is what you are doing)

**Comment by vasartori** [comment] 2020-12-08 20:58
coll @zyxep I'll take a look on it... thanks for your help

**Comment by vasartori** [comment] 2020-12-09 14:02
it works @zyxep thanks a lot!!!

**Comment by stanguturi** [comment] 2021-02-10 16:35
As @dsouders mentioned, this issue is really not related to open-vm-tools. Also, changing the controller type to "paravirtual scsci controller" had solved the issue. Closing. Thanks.

**Closed by stanguturi** 2021-02-10 16:35 UTC
