### ISSUE TITLE
configure.ac:1506: error

### ISSUE THREAD

**Issue by YingtongDou** [vmware/open-vm-tools#115] opened 2016-11-06 06:20 UTC
When I run autoreconf -i
The error information show below

<<<<
configure.ac:1506: error: required file 'common-agent/etc/config/Makefile.in' not found
common-agent/etc/Makefile.am:18: error: required directory common-agent/etc/config does not exist
<<<<

**Comment by vmwareopenvmtools** [comment] 2016-11-06 09:19
Hi Yingtong Dou,


"Makefile.in" and other temporary files are no longer in the repository, so they

are not present in the "stable-10.1.0.zip" and "stable-10.1.0.tar.gz" downloads.

To use those files you need to first run the "autoconf" command.


Please use "open-vm-tools-10.1.0-4449150.tar.gz<https://github.com/vmware/open-vm-tools/files/573466/open-vm-tools-10.1.0-4449150.tar.gz>", which is linked from the

release page,  if you need pre-configured Makefile.in files.


Doug


________________________________

**Comment by hooolden** [comment] 2016-11-08 16:23
What do we do in the situation that the version of autoconf/automake on our boxes are newer than the ones these were designed with?  

Is there an RPM package available?

**Comment by YingtongDou** [comment] 2016-11-08 17:54
I'll have a try, thank you!

**Comment by fusionneur** [comment] 2016-12-11 15:13
same error with latest build

**Comment by bosconi** [comment] 2016-12-29 14:24
Hi. I have encountered this issue while trying to debug another issue: https://github.com/vmware/open-vm-tools/issues/126

I'm trying to build on Ubuntu 16.04.1. Details of the environment, command lines I tried and output are in the comments on https://github.com/vmware/open-vm-tools/issues/126

Please let me know if you would like me to cross-post anything to this issue, or try anything else.

**Comment by ncopa** [comment] 2017-01-02 12:02
@vmwareopenvmtools The problem is that there is a reference[1] to a `common-agent/etc/config/Makefile.in` file in a non-existing[2] `common-agent/etc/config` directory.

--
[1]: https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/configure.ac#L1598
[2]: https://github.com/vmware/open-vm-tools/tree/master/open-vm-tools/common-agent/etc

**Comment by ncopa** [comment] 2017-01-02 12:06
There is also a reference to the missing `config` directory in https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/common-agent/etc/Makefile.am#L18

**Comment by oliverkurth** [comment] 2017-01-04 01:58
There were indeed missing files. This was caused by the entry 'config' in the .gitignore file. I just pushed a fix to the master branch with 5a9033ddfa95786d867e4d02bbb9a29bac8fb64f .

**Comment by oliverkurth** [comment] 2017-01-04 01:58
Feel free to reopen if this problem persists.

**Closed by oliverkurth** 2017-01-04 01:58 UTC
