### ISSUE TITLE
Upgrading to open-vm-tools 11.1.0 breaks vmhgfs-fuse

### ISSUE THREAD

**Issue by expickard** [vmware/open-vm-tools#454] opened 2020-08-04 22:00 UTC
Really weird issue here that I just spent a couple hours troubleshooting. Upgrading from 11.0.1-2 to 11.1.0-1 broke my ability to write large files to shared vm folders.
```

Host:
 OS: Manjaro Linux
 CPU: Threadripper 1950x
 Kernel: 5.4.52-1-MANJARO

Guest: 
 OS: Manjaro Linux
 Kernel: 5.4.52-1-MANJARO

VMware Workstation version: 15.5.2 build-15785246
```

What happens is that any file over 1-3kb generates an I/O error (error splicing file, according to the GUI). I tried a bunch of different options: 
`vmhgfs-fuse -o allow_other -o auto_unmount -o big_writes -o direct_io -o large_read -d .host:/extshare /home/user/extshare/`
 to no avail. 

When using -d, all I can see is an attempt to write to a file that generates a status code -5. If I downgrade to 11.0.1-2 and restart the relevant services, remount the shares, and try again, I don't get any errors. 

Please let me know what I can do to help debug this-- I'm aware this is probably not enough information.

**Comment by dsouders** [comment] 2020-08-04 23:27
@expickard 

This is likely the same as issue #437, https://github.com/vmware/open-vm-tools/issues/437.
There is already an internal bug tracking that problem.
Could you please see if the workaround in https://kb.vmware.com/s/article/74650 fixes your issue?

**Comment by expickard** [comment] 2020-08-05 01:02
Unit file created. Rebooted.
Validated it starts properly. 
Toggled shared folders, restarted the arch/manjaro vmware services (vmtoolsd, vmware-vmblock-fuse, and mnt-hgfs). 
Validated fuse is loaded with lsmod.
I'm still getting the same error.

If it's being worked on already, though, this issue report is probably not helpful. I can stay downgraded for a bit unless there's further troubleshooting to be done.

**Comment by horshack-dpreview** [comment] 2020-08-06 12:49
FYI I discovered the bug occurs for vmhgfs-fuse I/O sizes >= 64K. You can work around the issue by adding a max_write=61440 to the mount options in fstab (64K - 4K). For example:

.host:/ /mnt/hgfs fuse.vmhgfs-fuse noauto,allow_other,max_write=61440 0 0

More details here: https://github.com/vmware/open-vm-tools/issues/437#issuecomment-669663891

**Comment by stanguturi** [comment] 2021-02-08 22:33
> @expickard
> 
> This is likely the same as issue #437.
> There is already an internal bug tracking that problem.
> Could you please see if the workaround in https://kb.vmware.com/s/article/74650 fixes your issue?

Closing this issue since this is a duplicate of #437 .

**Closed by stanguturi** 2021-02-08 22:33 UTC
