### ISSUE TITLE
Kernel panic triggered by vMotion between ESXi 6.0 host and ESXi 5.5 host

### ISSUE THREAD

**Issue by jwhite530** [vmware/open-vm-tools#88] opened 2016-05-06 15:58 UTC
I have a VMware cluster of two hosts and a dozen or so VMs, all running CentOS 7 x86_64.  The hosts are running:

host1: ESXi 6.0 (3380124)
host2: ESXi 5.5 (3568722)

We issued a vMotion of all VMs, which were running on host1, to move to host2.  Most of the VMs had a kernel panic and crashed as they were being moved.  All of the VMs that crashed were running open-vm-tools, the VMs that did not crash were not running open-vm-tools.  I have a kernel crash dump I can provide for analysis if someone can let me know where I can host it (43MB compressed).

I am not a kernel developer so I can't help debug this problem very much but I do see what appears to be VMware's software (things prefixed with "vmw" and such) which I assume to be open-vm-tools in the backtrace in the crash dump:

> crash> bt
> PID: 2130   TASK: ffff8800b7483980  CPU: 0   COMMAND: "mysqld"
>  #0 [ffff8800bf803ab8] machine_kexec at ffffffff81051beb
>  #1 [ffff8800bf803b18] crash_kexec at ffffffff810f2542
>  #2 [ffff8800bf803be8] oops_end at ffffffff8163e128
>  #3 [ffff8800bf803c10] no_context at ffffffff8162e278
>  #4 [ffff8800bf803c60] __bad_area_nosemaphore at ffffffff8162e30e
>  #5 [ffff8800bf803ca8] bad_area_nosemaphore at ffffffff8162e478
>  #6 [ffff8800bf803cb8] __do_page_fault at ffffffff81640f2e
>  #7 [ffff8800bf803d18] do_page_fault at ffffffff816410c3
>  #8 [ffff8800bf803d40] page_fault at ffffffff8163d388
>     [exception RIP: unknown or invalid address]
>     RIP: 0000000000000000  RSP: ffff8800bf803df0  RFLAGS: 00010293
>     RAX: 0000000000000000  RBX: ffffffffa0323190  RCX: 0000000000000000
>     RDX: ffffffffa03235cf  RSI: ffffffffa03235c0  RDI: ffffffffa0323190
>     RBP: ffff8800bf803e00   R8: 00067f981e196040   R9: 0000000000001000
>     R10: 0000000000000000  R11: 0000000000000005  R12: ffffffffa027ce10
>     R13: ffffc90008731040  R14: 0000000000000fd8  R15: 0000000000000020
>     ORIG_RAX: ffffffffffffffff  CS: 0010  SS: 0018
>  #9 [ffff8800bf803df0] vmci_transport_handle_detach at ffffffffa027ce55 [vmw_vsock_vmci_transport]
> #10 [ffff8800bf803e08] vsock_for_each_connected_socket at ffffffffa031f28a [vsock]
> #11 [ffff8800bf803e28] vmci_transport_qp_resumed_cb at ffffffffa027c6e5 [vmw_vsock_vmci_transport]
> #12 [ffff8800bf803e38] vmci_event_dispatch at ffffffffa02b1c74 [vmw_vmci]
> #13 [ffff8800bf803e70] vmci_dispatch_dgs at ffffffffa02b1f94 [vmw_vmci]
> #14 [ffff8800bf803eb0] tasklet_action at ffffffff8108495d
> #15 [ffff8800bf803ed8] __do_softirq at ffffffff81084b0f
> #16 [ffff8800bf803f48] call_softirq at ffffffff816471dc
> #17 [ffff8800bf803f60] do_softirq at ffffffff81016fc5
> #18 [ffff8800bf803f80] irq_exit at ffffffff81084ea5
> #19 [ffff8800bf803f98] smp_apic_timer_interrupt at ffffffff81647e55

So, I believe open-vm-tools is what caused this kernel panic.  Please let me know what further information you need from me to resolve the problem.

**Comment by jwhite530** [comment] 2016-05-06 16:28
Additional information from one of the machines which crashed:

> KERNEL: /usr/lib/debug/lib/modules/3.10.0-327.4.5.el7.x86_64/vmlinux
> DUMPFILE: /var/crash/127.0.0.1-2016-05-05-15:12:26/vmcore  [PARTIAL DUMP]
> CPUS: 2
> DATE: Thu May  5 15:13:07 2016
> UPTIME: 21 days, 04:05:41
> LOAD AVERAGE: 0.00, 0.01, 0.05
> TASKS: 255
> NODENAME: slurm-p1n01.removed
> RELEASE: 3.10.0-327.4.5.el7.x86_64
> VERSION: #1 SMP Mon Jan 25 22:07:14 UTC 2016
> MACHINE: x86_64  (2499 Mhz)
> MEMORY: 3 GB
> PANIC: "BUG: unable to handle kernel NULL pointer dereference at           (null)"
> PID: 2130
> COMMAND: "mysqld"
> TASK: ffff8800b7483980  [THREAD_INFO: ffff8800b9630000]
> CPU: 0
> STATE: TASK_RUNNING (PANIC)

> $ rpm -q open-vm-tools
> open-vm-tools-9.10.2-4.el7.x86_64

**Comment by oliverkurth** [comment] 2016-05-06 16:32
Thanks jwhite for reporting this!

We need some more information:
- did you install open-vm-tools using the CentOS packages, or build from source?
- what version of open-vm-tools is this (you can use the command 'vmtoolsd -v' or 'rpm -qi open-vm-tools')?
- what kernel version ('uname -a')

I will get to you later, and let you know if you can upload the crash dump somewhere.

**Comment by jwhite530** [comment] 2016-05-06 16:33
I posted another comment just before yours with the version information you requested.  I installed the software using the package provided from CentOS repos, not from source.

**Comment by oliverkurth** [comment] 2016-05-06 16:37
Thanks for the additional information! I didn't see that comment yet when I posted mine.

**Comment by oliverkurth** [comment] 2016-05-06 17:53
Unfortunately I wasn't able to find a way for you to upload the file directly to VMware. Could you upload the dump to google drive or dropbox, and post the link?

If it contains sensitive information, we can figure out a way for you to encrypt the file.

**Comment by jwhite530** [comment] 2016-05-06 18:55
This link should provide the compressed vmcore of one of the machines which crashed:

https://drive.google.com/open?id=0B6emnuNXtougSC1uYzlpOEZYcEk

**Comment by oliverkurth** [comment] 2016-05-06 19:48
Thank you for the core file! Got it.

**Comment by jsvaerke** [comment] 2016-05-23 14:37
The issue has been identified as a bug in the vsock kernel module that is part of the Linux kernels version 3.9 and 3.10. The issue is fixed in kernels version 3.11 and later through [this](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=d9af2d67e490b48f0d36f448d34e7bab9425f142).

We (VMware) will work with distros to get the fix backported.

open-vm-tools triggers this issue, because open-vm-tools uses vsock on ESX 6.0 hosts and later for hypervisor communication.

**Comment by ravindravmw** [comment] 2016-06-16 01:01
@jwhite530 please raise the bug with your distro maintainers to pick up the Linux kernel fix jsvaerke mentioned.

**Closed by ravindravmw** 2016-06-16 01:01 UTC

**Comment by jsvaerke** [comment] 2016-06-24 09:18
I've filed a bug with Redhat to get this issue corrected.
